const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.join(__dirname,'..','premium-v2'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
for(const f of ['spm-resources-content.js','spm-resources.js','spm-visual-cards-staging-v4.js','spm-nutrition-premium-images-v1.js','wellness-daily-tip-v1.js','wellness-library-v1.js','sleep-library-v1.js'])assert.doesNotThrow(()=>new Function(read(f)),f+' parse');
const C=read('spm-resources-content.js'),R=read('spm-resources.js'),V=read('spm-visual-cards-staging-v4.js'),N=read('spm-nutrition-premium-images-v1.js'),W=read('wellness-daily-tip-v1.js'),H=read('wellness-library-v1.js'),S=read('sleep-library-v1.js'),L=read('live.html');
for(const id of ['vegetables','fruit','protein','pulses','fats','limit'])assert(C.includes("id:'"+id+"'"),'missing food '+id);
assert(C.includes('Brócoli | espinaca')&&C.includes('Aceite de oliva | aguacate'),'expanded nutrition lists missing');
for(const id of ['walk','strength','mobility','kegel','swim','dance'])assert(C.includes("id:'"+id+"'"),'missing movement card '+id);
assert(!C.includes("id:'jog'")&&!C.includes("id:'bike'"),'Movement must expose exactly six approved cards');
for(const pair of [["walk","01-caminata-cardio-moderado.jpg"],["strength","02-entrenamiento-fuerza.jpg"],["mobility","03-movilidad-flexibilidad.jpg"],["kegel","06-piso-pelvico-kegel.jpg"],["swim","04-actividad-en-el-agua.jpg"],["dance","05-bailar-y-moverte.jpg"]])assert(V.includes(pair[0]+":'"+pair[1]+"'"),'visual mapping missing '+pair[0]);
for(const f of ['spm-nutrition-master.webp','spm-nutrition-fats.webp'])assert(fs.existsSync(path.join(root,'assets/nutrition',f)),'nutrition visual missing '+f);
for(const f of ['02-verduras.jpg','03-frutas.jpg','04-proteinas-saludables.jpg','05-legumbres-e-integrales.jpg','06-grasas-insaturadas.jpg','07-alimentos-y-bebidas-a-limitar.jpg'])assert(fs.existsSync(path.join(root,'assets/nutrition/cards-v1',f)),'nutrition card missing '+f);
for(const f of ['01-caminata-cardio-moderado.jpg','02-entrenamiento-fuerza.jpg','03-movilidad-flexibilidad.jpg','04-actividad-en-el-agua.jpg','05-bailar-y-moverte.jpg','06-piso-pelvico-kegel.jpg'])assert(fs.existsSync(path.join(root,'assets/activity/cards-v1',f)),'movement card missing '+f);
assert(N.includes('spm-nutrition-master.webp')&&N.includes('spm-plate-premium'),'Plato SPM visual system missing');
assert(W.includes("const ORDER=['nutrition','movement','sleep']"),'wellness rotation must be Nutrition Movement Sleep');
assert(W.includes("SPM_RESOURCES.open('nutrition'")&&W.includes("SPM_RESOURCES.open('movement'")&&W.includes('SPM_SLEEP_LIBRARY_V1'),'daily tips not linked to all three resources');
assert(R.includes('wellnessLibrary')&&R.includes('Volver a Nutrición')&&R.includes('Volver a Movimiento'),'Nutrition/Movement navigation hierarchy missing');
assert(H.includes('Nutrición SPM')&&H.includes('Movimiento SPM')&&H.includes('Sueño SPM')&&H.includes('SPM_SLEEP_LIBRARY_V1'),'Wellness library integration incomplete');
for(const term of ['sl-horario-01','sl-pantallas-01','sl-habitacion-01','sl-despertares-02','Volver a Sueño','Volver a Biblioteca Bienestar','Volver a Hoy'])assert(S.includes(term),'Sleep library missing '+term);
for(const s of ['spm-visual-cards-staging-v4.js','spm-nutrition-premium-images-v1.js','sleep-library-v1.js','wellness-library-v1.js','wellness-daily-tip-v1.js'])assert(L.includes(s),'live missing '+s);
console.log('Wellness static QA OK: Nutrition + six-card Movement + Sleep + 28-day rotation + return navigation');