const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.join(__dirname,'..','premium-v2'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
const js=['spm-resources-content.js','spm-resources.js','spm-visual-cards-staging-v4.js','spm-nutrition-premium-images-v1.js','wellness-daily-tip-v1.js','wellness-library-v1.js','sleep-library-v1.js'];
for(const f of js)assert.doesNotThrow(()=>new Function(read(f)),f+' parse');
const C=read('spm-resources-content.js'),R=read('spm-resources.js'),V=read('spm-visual-cards-staging-v4.js'),N=read('spm-nutrition-premium-images-v1.js'),W=read('wellness-daily-tip-v1.js'),H=read('wellness-library-v1.js'),S=read('sleep-library-v1.js'),L=read('live.html');
assert(fs.existsSync(path.join(root,'assets/nutrition/plato-spm-final.webp')),'approved Plato SPM asset missing');
assert(N.includes("plato-spm-final.webp"),'Plato renderer is not using approved final asset');
assert(N.includes('spm-plate-final'),'final Plato component missing');
for(const id of ['vegetables','fruit','protein','pulses','fats','limit'])assert(C.includes("id:'"+id+"'"),'missing food '+id);
assert(R.includes('sr-nut-mid')&&R.includes('sr-nut-chips')&&R.includes('Idea para hoy'),'Oasis Nutrition detail composition missing');
assert(R.includes("NUT_VISUAL={vegetables:")&&R.includes("limit:'assets/nutrition/cards-v1/07-alimentos-y-bebidas-a-limitar.jpg'"),'Nutrition mid-image mapping incomplete');
assert(V.includes(".sr-nut-grid button[data-food]"),'visual loader should only decorate Nutrition home cards');
assert(!V.includes("document.querySelectorAll('.sr-dialog button[data-food]')"),'legacy broad Nutrition loader still touches Plato/details');
for(const id of ['walk','strength','mobility','kegel','swim','dance'])assert(C.includes("id:'"+id+"'"),'missing movement card '+id);
assert(!C.includes("id:'jog'")&&!C.includes("id:'bike'"),'Movement must expose exactly six approved cards');
assert(H.includes('OASIS DE BIENESTAR')&&H.includes('tone-nutrition')&&H.includes('tone-movement')&&H.includes('tone-sleep'),'Wellness Oasis design missing');
assert(S.includes('slNightVisual')&&S.includes('const ICON=')&&S.includes('const TONE='),'Sleep visual Oasis layer missing');
assert(W.includes("const ORDER=['nutrition','movement','sleep']"),'wellness rotation must be Nutrition Movement Sleep');
assert(W.includes('spm-wellness-tip-icon')&&W.includes('data-category'),'daily Wellness visual state missing');
for(const s of ['spm-nutrition-premium-images-v1.js?v=20261001-oasis1','sleep-library-v1.js?v=20261001-oasis1','wellness-library-v1.js?v=20261001-oasis1','wellness-daily-tip-v1.js?v=20261001-oasis1'])assert(L.includes(s),'live cache wiring missing '+s);
console.log('Wellness Oasis static QA OK');