const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.join(__dirname,'..','premium-v2'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
const jsFiles=['spm-resources-content.js','spm-resources.js','spm-visual-cards-staging-v4.js','recovery-story-premium-v4.js','recovery-story-extra-v1.js','recovery-media-local-staging-v4.js','recovery-audio-controller-staging-v10.js','spm-inline-video-player.js'];
for(const f of jsFiles){assert(fs.existsSync(path.join(root,f)),f+' missing');assert.doesNotThrow(()=>new Function(read(f)),f+' must parse');}
assert(fs.existsSync(path.join(root,'spm-resources.css')),'spm-resources.css missing');
const nutrition=['01-plato-spm.jpg','02-verduras.jpg','03-frutas.jpg','04-proteinas-saludables.jpg','05-legumbres-e-integrales.jpg','06-grasas-insaturadas.jpg','07-alimentos-y-bebidas-a-limitar.jpg'];
for(const f of nutrition)assert(fs.existsSync(path.join(root,'assets/nutrition/cards-v1',f)),'nutrition asset missing '+f);
const activity=['01-caminata-cardio-moderado.jpg','02-entrenamiento-fuerza.jpg','03-movilidad-flexibilidad.jpg','04-actividad-en-el-agua.jpg','05-bailar-y-moverte.jpg','06-piso-pelvico-kegel.jpg'];
for(const f of activity)assert(fs.existsSync(path.join(root,'assets/activity/cards-v1',f)),'movement asset missing '+f);
const aud=['before','condom','during','early','next','partner','urge'];
for(const id of aud)assert(fs.existsSync(path.join(root,'assets/audio','recovery-patient-'+id+'-es.mp3')),'recovery audio missing '+id);
for(const f of ['recovery-patient-master.mp4','dr-spm-medications-content.mp4','dr-spm-metabolic-content.mp4','dr-spm-performance-anxiety-content.mp4','dr-spm-vascular-content.mp4'])assert(fs.existsSync(path.join(root,'assets/videos',f)),'video missing '+f);
const core=read('recovery-story-premium-v4.js'),extra=read('recovery-story-extra-v1.js'),content=read('spm-resources-content.js'),visual=read('spm-visual-cards-staging-v4.js'),player=read('spm-inline-video-player.js');
for(const id of ['condom','before','during'])assert(core.includes(id+':{title'),'core recovery story missing '+id);
for(const id of ['early','urge','partner','next'])assert(extra.includes(id+':{title'),'extra recovery story missing '+id);
for(const id of ['condom','before','during','early','urge','partner','next'])assert(content.includes("id:'"+id+"'"),'resource scenario missing '+id);
for(const f of nutrition)assert(visual.includes(f),'visual loader missing '+f);
assert(player.includes("dr-spm-$1-content.mp4"),'Doctor SPM content-video rewrite missing');
const live=read('live.html');for(const s of ['spm-visual-cards-staging-v4.js','recovery-story-premium-v4.js','recovery-story-extra-v1.js','recovery-media-local-staging-v4.js','recovery-audio-controller-staging-v10.js'])assert(live.includes(s),'live integration missing '+s);
console.log('Premium resources static QA OK: Recovery 7 stories/audio/avatar, Nutrition 7 cards, Movement premium cards, Doctor SPM cropped videos.');