const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {JSDOM}=require('../labs/desire/node_modules/jsdom');
const source=fs.readFileSync(path.join(__dirname,'../premium-v2/sensate-lab-bridge-v1.js'),'utf8');
function harness(extra={}){
 const dom=new JSDOM('<section id="plan"><div class="dayCard"></div></section><button id="logoutBtn">Salir</button>',{url:'https://spm.test/premium-v2/live.html',runScripts:'outside-only',pretendToBeVisual:true});
 const w=dom.window;w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};
 let c={userId:'qa',planId:'p1',day:12,safety:'none',flags:[],checkins:[],primary:'erection',secondary:'desire',motives:['erection','desire'],...extra};const writes=[];
 w.SPM_RESOURCE_CONTEXT=()=>c;w.SPM_SENSATE_RECORDS={read:async()=>({}),save:async(state,scope,day)=>writes.push({state,scope,day})};w.eval(source);
 return {w,writes,context:()=>c,setContext:next=>{c=next},async close(){await w.SPM_SENSATE_LAB.close();w.close();}};
}
test('DE + deseo and EP + deseo link to the module using the active Central day',async()=>{
 for(const primary of ['erection','ejaculation']){const h=harness({primary});try{assert.equal(h.w.SPM_SENSATE_LAB.relevant(h.context()),true);await new Promise(r=>setTimeout(r,30));assert.ok(h.w.document.querySelector('[data-sensate-daily]'));await h.w.SPM_SENSATE_LAB.open({origin:primary==='erection'?'erectile':'ejaculation',day:27});assert.equal(h.w.SPM_SENSATE_LAB_HOST.getContext().day,12);assert.match(h.w.document.querySelector('iframe').src,/origin=dailyPlan/);}finally{await h.close();}}
});
test('a standalone primary Sensate route is relevant; unrelated profiles remain optional',async()=>{const h=harness();try{assert.equal(h.w.SPM_SENSATE_LAB.relevant({primary:'desire'}),true);assert.equal(h.w.SPM_SENSATE_LAB.relevant({primary:'unrelated'}),false);}finally{await h.close();}});
test('module state is saved under the active user/plan and never browser local storage',async()=>{const h=harness();try{await h.w.SPM_SENSATE_LAB.open();assert.equal(h.w.SPM_SENSATE_LAB_HOST.write('spm-sensate-state','{"zones":["neck"]}'),true);await h.w.SPM_SENSATE_LAB.flush();assert.equal(h.writes[0].scope,'qa:p1');assert.equal(h.writes[0].day,12);assert.equal(h.w.localStorage.length,0);assert.equal(h.writes[0].state['spm-sensate-state'],'{"zones":["neck"]}');}finally{await h.close();}});
test('account changes invalidate the old bridge and pending writes',async()=>{const h=harness();try{await h.w.SPM_SENSATE_LAB.open();const old=h.w.SPM_SENSATE_LAB_HOST;h.setContext({...h.context(),userId:'other'});assert.equal(old.write('spm-sensate-state','7'),false);h.w.dispatchEvent(new h.w.Event('spm:session-change'));assert.equal(h.w.SPM_SENSATE_LAB_HOST,undefined);assert.equal(h.writes.length,0);}finally{await h.close();}});
test('save failure retains the module for retry and does not claim success',async()=>{const h=harness();try{await h.w.SPM_SENSATE_LAB.open();h.w.SPM_SENSATE_LAB_HOST.write('spm-sensate-state','7');h.w.SPM_SENSATE_RECORDS.save=async()=>{throw Error('offline')};assert.equal(await h.w.SPM_SENSATE_LAB.close(),false);assert.ok(h.w.document.querySelector('iframe'));assert.equal(h.w.document.querySelector('[data-sensate-retry]').hidden,false);h.w.SPM_SENSATE_RECORDS.save=async()=>{};assert.equal(await h.w.SPM_SENSATE_LAB.close(),true);}finally{await h.close();}});
test('clinical review and urgent signals reach the child without changing scores or days',async()=>{const h=harness();try{await h.w.SPM_SENSATE_LAB.open();h.setContext({...h.context(),safety:'review'});assert.equal(h.w.SPM_SENSATE_LAB_HOST.getContext().restriction,'review');h.setContext({...h.context(),safety:'urgent'});assert.equal(h.w.SPM_SENSATE_LAB_HOST.getContext().restriction,'urgent');assert.equal(h.writes.length,0);}finally{await h.close();}});
test('read failures do not initialize empty data over existing progress',async()=>{const h=harness();try{h.w.SPM_SENSATE_RECORDS.read=async()=>{throw Error('offline')};assert.equal(await h.w.SPM_SENSATE_LAB.open(),false);assert.equal(h.w.SPM_SENSATE_LAB_HOST,undefined);assert.equal(h.w.document.querySelector('iframe'),null);assert.equal(h.writes.length,0);}finally{await h.close();}});
test('new transversal events open Sensate and unknown state keys are rejected',async()=>{const h=harness();try{h.w.dispatchEvent(new h.w.CustomEvent('spm:open-lab',{detail:{lab:'sensate',origin:'erectile'}}));await new Promise(r=>setTimeout(r,0));assert.ok(h.w.document.querySelector('iframe'));assert.equal(h.w.SPM_SENSATE_LAB_HOST.write('userId','other'),false);assert.equal(h.w.SPM_SENSATE_LAB.validState({'spm-sensate-records':'x'.repeat(350001)}),false);}finally{await h.close();}});

test('all intended routes share Central day and clinical content stays intact',async()=>{for(const primary of ['erection','ejaculation','desire','confidence','anxiety']){const h=harness({primary});try{assert.equal(h.w.SPM_SENSATE_LAB.relevant(h.context()),true);await h.w.SPM_SENSATE_LAB.open();assert.equal(h.w.SPM_SENSATE_LAB_HOST.getContext().day,12);}finally{await h.close();}} const source=fs.readFileSync(path.join(__dirname,'../labs/sensate/src/components/SensateLab.tsx'),'utf8');assert.doesNotMatch(source,/<pre|localStorage/);assert.match(source,/day: centralContext\(\).day/);assert.match(source,/await host\(\)\?\.flush/);});
