(()=>{
const E=window.ENGINE||{assessment:{questions:[]}}, M=window.SPM_MODULES;
const $=id=>document.getElementById(id);
const state={lang:'es',motives:[],queue:[],answers:{},qi:0,map:null,phase:1,coach:[],completedDays:new Set()};
const motives=[
 {id:'erection',es:'Erección o firmeza',en:'Erection or firmness',desc:'Dificultad para iniciar, mantener o conservar firmeza.'},
 {id:'ejaculation',es:'Control eyaculatorio',en:'Ejaculatory control',desc:'Eyaculación antes de lo deseado o poco control.'},
 {id:'desire',es:'Deseo o excitación',en:'Desire or arousal',desc:'Menor interés, activación o respuesta de excitación.'},
 {id:'confidence',es:'Confianza / ansiedad de desempeño',en:'Confidence / performance anxiety',desc:'Presión, vigilancia, miedo a fallar o evitación.'},
 {id:'wellbeing',es:'Satisfacción y conexión',en:'Satisfaction and connection',desc:'Quiero mejorar calidad, comunicación o disfrute.'},
 {id:'optimization',es:'Quiero mejorar o conservar mi desempeño',en:'I want to improve or preserve performance',desc:'No tengo un problema claro; busco optimización y prevención.'}
];
function start(){ $('landing').style.display='none'; $('app').style.display='block'; window.scrollTo({top:0,behavior:'smooth'}); }
['topStart','heroStart'].forEach(id=>$(id)?.addEventListener('click',start));
$('learnBtn')?.addEventListener('click',()=>document.getElementById('how')?.scrollIntoView({behavior:'smooth'}));
$('langBtn')?.addEventListener('click',()=>{state.lang=state.lang==='es'?'en':'es';$('langBtn').textContent=state.lang==='es'?'EN':'ES';renderMotives(); if(!cycleHidden('quizCard')) renderQuestion(); if(state.map) renderMap(); renderPlan();});
function cycleHidden(id){return $(id)?.hidden!==false}
function renderMotives(){const g=$('motiveGrid'); if(!g)return; g.innerHTML=''; motives.forEach(m=>{const b=document.createElement('button');b.className='choice'+(state.motives.includes(m.id)?' sel':'');b.type='button';b.innerHTML=`<b>${state.lang==='es'?m.es:m.en}</b><span>${m.desc}</span>`;b.addEventListener('click',()=>{const i=state.motives.indexOf(m.id);i>=0?state.motives.splice(i,1):state.motives.push(m.id);renderMotives()});g.appendChild(b)});}
renderMotives();
document.querySelectorAll('[data-age]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.age==='1'){$('ageCard').hidden=true;$('motiveCard').hidden=false;renderMotives();}else alert('SPM está diseñado para mayores de 18 años.')}));
$('motiveBack')?.addEventListener('click',()=>{$('motiveCard').hidden=true;$('ageCard').hidden=false});
$('motiveNext')?.addEventListener('click',()=>{if(!state.motives.length){alert('Selecciona al menos una opción.');return;}buildQueue();state.qi=0;$('motiveCard').hidden=true;$('quizCard').hidden=false;renderQuestion();});
function buildQueue(){
 const sections=new Set(['goal','lifestyle','health','pelvic_floor','safety']);
 state.motives.forEach(m=>{if(m!=='optimization')sections.add(m)});
 if(state.motives.includes('optimization'))['confidence','wellbeing','desire'].forEach(s=>sections.add(s));
 state.queue=E.assessment.questions.filter(q=>sections.has(q.section));
}
function scaleOptions(reverse=false){return [1,2,3,4,5].map(v=>({value:v,label:state.lang==='es'?['Muy bajo / nunca','Bajo / rara vez','Intermedio','Bueno / frecuente','Muy bueno / casi siempre'][v-1]:['Very low / never','Low / rarely','Mid','Good / often','Very good / almost always'][v-1]}));}
function renderQuestion(){const q=state.queue[state.qi];if(!q)return finishAssessment();$('qCount').textContent=`${state.qi+1} / ${state.queue.length}`;$('prog').style.width=`${((state.qi+1)/state.queue.length)*100}%`;$('qSection').textContent=q.section.replace('_',' ');$('qRoute').textContent='SPM Adaptive';const box=$('qbox');box.innerHTML=`<h3 class="qtitle">${state.lang==='es'?q.prompt_es:q.prompt_en}</h3>`;let opts=[];if(q.type==='scale5'||q.type==='scale5_reverse')opts=scaleOptions();else if(q.type==='boolean')opts=[{value:false,label:state.lang==='es'?'No':'No'},{value:true,label:state.lang==='es'?'Sí':'Yes'}];else opts=(q.options||[]).map(o=>({value:o.value,label:state.lang==='es'?o.es:o.en}));const wrap=document.createElement('div');wrap.className='opts '+((q.type||'').startsWith('scale')?'scale':q.type==='boolean'?'binary':'single');opts.forEach(o=>{const b=document.createElement('button');b.type='button';b.className='opt'+(String(state.answers[q.id])===String(o.value)?' sel':'');b.innerHTML=((q.type||'').startsWith('scale')?`<b>${o.value}</b><span>${o.label}</span>`:`<span>${o.label}</span>`);b.addEventListener('click',()=>{state.answers[q.id]=o.value;renderQuestion()});wrap.appendChild(b)});box.appendChild(wrap);$('qBack').disabled=state.qi===0;}
$('qBack')?.addEventListener('click',()=>{if(state.qi>0){state.qi--;renderQuestion();}});
$('qNext')?.addEventListener('click',()=>{const q=state.queue[state.qi];if(state.answers[q.id]===undefined){alert(state.lang==='es'?'Selecciona una respuesta.':'Choose an answer.');return;}state.qi++;renderQuestion();});
function scoreMap(){const domains={};state.queue.forEach(q=>{if(!q.domain||state.answers[q.id]===undefined)return;let v=Number(state.answers[q.id]);if(!Number.isFinite(v))return;if(q.type==='scale5_reverse')v=6-v;const s=(v-1)*25,w=q.weight||1;if(!domains[q.domain])domains[q.domain]={sum:0,w:0};domains[q.domain].sum+=s*w;domains[q.domain].w+=w;});const scores={};Object.entries(domains).forEach(([k,v])=>scores[k]=Math.round(v.sum/v.w));const core=['erection','ejaculation','desire','confidence','wellbeing','lifestyle'].filter(k=>scores[k]!=null);let ranked=core.sort((a,b)=>scores[a]-scores[b]);let primary=ranked[0]||'lifestyle',secondary=ranked[1]||null;if(state.motives.includes('optimization')&&ranked.length&&scores[primary]>65)primary='lifestyle';const urgent=state.queue.filter(q=>q.safety==='urgent'&&state.answers[q.id]===true),review=state.queue.filter(q=>q.safety==='review'&&state.answers[q.id]===true);return {scores,primary,secondary,urgent,review,total:Math.round(core.reduce((a,k)=>a+scores[k],0)/(core.length||1))};}
function finishAssessment(){state.map=scoreMap();['navMap','navPlan','navCoach','navProgress'].forEach(id=>$(id).disabled=false);showPanel('map');renderMap();renderPlan();populateCoachDays();}
function showPanel(id){document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('on',p.id===id));document.querySelectorAll('.navbtn').forEach(b=>b.classList.toggle('on',b.dataset.panel===id));window.scrollTo({top:0,behavior:'smooth'});}
document.querySelectorAll('.navbtn').forEach(b=>b.addEventListener('click',()=>!b.disabled&&showPanel(b.dataset.panel)));
$('goPlan')?.addEventListener('click',()=>showPanel('plan'));
function profileLabel(k){return M.profiles[k]?.[state.lang==='es'?'label_es':'label_en']||k;}
function renderMap(){const m=state.map;if(!m)return;const sb=$('safetyBox');if(m.urgent.length)sb.innerHTML='<div class="notice danger"><b>Prioridad de seguridad.</b> Tus respuestas incluyen una señal que requiere atención médica urgente antes de continuar con entrenamiento autoguiado.</div>';else if(m.review.length)sb.innerHTML='<div class="notice warn"><b>Revisión clínica recomendada.</b> Hay datos que conviene revisar con un profesional mientras continúas solo con módulos seguros.</div>';else sb.innerHTML='<div class="notice good"><b>Sin banderas mayores detectadas en este tamizaje.</b> Esto no sustituye una valoración médica.</div>';$('scoreValue').textContent=m.total;$('scoreRing').style.setProperty('--pct',m.total);$('profileTitle').textContent=profileLabel(m.primary);$('profileExplain').textContent=state.lang==='es'?`Tu prioridad educativa principal aparece en ${profileLabel(m.primary).toLowerCase()}${m.secondary?`, con un componente secundario en ${profileLabel(m.secondary).toLowerCase()}`:''}. Este mapa orienta qué habilidades se entrenan primero; no es un diagnóstico.`:`Your main educational priority is ${profileLabel(m.primary).toLowerCase()}. This is not a diagnosis.`;const dg=$('domainGrid');dg.innerHTML='';Object.entries(m.scores).filter(([k])=>['erection','ejaculation','desire','confidence','wellbeing','lifestyle'].includes(k)).forEach(([k,v])=>{const d=document.createElement('div');d.className='domain';d.innerHTML=`<div class="domainHead"><b>${profileLabel(k)}</b><span>${v}/100</span></div><div class="bar"><i style="width:${v}%"></i></div>`;dg.appendChild(d)});$('whyList').innerHTML=`<div class="mini"><small>Driver principal</small><p>${profileLabel(m.primary)} fue el dominio con mayor margen de trabajo dentro de las áreas evaluadas.</p></div>${m.secondary?`<div class="mini"><small>Driver secundario</small><p>${profileLabel(m.secondary)} puede modificar la respuesta del driver principal.</p></div>`:''}`;$('modifierList').innerHTML=`<div class="mini"><small>Contexto</small><p>Sueño, estrés, hábitos, confianza y seguridad se usan para adaptar intensidad y progresión.</p></div><div class="mini"><small>Fortalezas</small><p>Los dominios con mayor puntuación se conservan como recursos, no se convierten automáticamente en “tratamiento”.</p></div>`;$('week1Rationale').textContent=`La Semana 1 prioriza línea de base, regulación y reconocimiento del patrón antes de intensificar ejercicios para ${profileLabel(m.primary).toLowerCase()}.`;}
function profilePractice(day){const p=state.map?.primary||'lifestyle';const txt={erection:'Practica recuperación de firmeza sin “comprobar” continuamente: respiración, cambio de estímulo y retorno a sensaciones agradables.',ejaculation:'Practica reconocimiento de excitación y control de ritmo antes del punto de inevitabilidad; usa pausas solo como entrenamiento, no como examen.',desire:'Practica activación de deseo identificando facilitadores reales y reduciendo presión por “tener ganas” de inmediato.',confidence:'Practica desactivar monitoreo de desempeño y volver a sensaciones, respiración y conexión.',wellbeing:'Practica comunicación y focalización sensorial orientadas a disfrute, no a resultado.',lifestyle:'Practica el hábito protector con mayor margen: sueño, actividad física, estrés o consumo.'};return txt[p]||txt.lifestyle;}
function renderPlan(){if(!M||!$('phaseTabs'))return;const tabs=$('phaseTabs');tabs.innerHTML='';M.phases.forEach(ph=>{const b=document.createElement('button');b.className='phaseBtn'+(state.phase===ph.id?' on':'');b.textContent=`${ph.id}. ${state.lang==='es'?ph.name_es:ph.name_en}`;b.addEventListener('click',()=>{state.phase=ph.id;renderPlan()});tabs.appendChild(b)});const ph=M.phases.find(x=>x.id===state.phase);$('weekIntro').innerHTML=`<b>${state.lang==='es'?ph.name_es:ph.name_en}</b> · ${state.lang==='es'?ph.intro_es:ph.intro_en}`;const g=$('dayGrid');g.innerHTML='';M.days.filter(x=>ph.days.includes(x.d)).forEach(day=>{const c=document.createElement('div');c.className='dayCard';const practice=day.interaction==='profileSkill'?profilePractice(day.d):day.practice_es;c.innerHTML=`<div class="dayTop"><div class="dayNum">${day.d}</div><div><h4>${day.title_es}</h4><p>${day.learn_es.slice(0,105)}…</p></div><span class="tag">${profileLabel(state.map?.primary||'lifestyle')}</span></div><div class="dayBody"><div class="lessonFlow"><div class="lesson"><b>Aprender</b><p>${day.learn_es}</p></div><div class="lesson"><b>Practicar</b><p>${practice}</p></div><div class="lesson"><b>Medir</b><p>${day.measure_es}</p></div><div class="lesson"><b>Aplicar</b><p>${day.apply_es}</p></div><div class="lesson"><b>Completar</b><p>${day.complete_es}</p></div></div><div class="moduleMeta"><span class="chip">Día ${day.d}</span><span class="chip">${day.interaction}</span><span class="chip">Adaptado a ${profileLabel(state.map?.primary||'lifestyle')}</span></div><div class="interactive"></div></div>`;c.querySelector('.dayTop').addEventListener('click',()=>c.classList.toggle('open'));renderInteraction(c.querySelector('.interactive'),day);g.appendChild(c)});}
function renderInteraction(el,day){const doneBtn=()=>{const b=document.createElement('button');b.className='btn pri';b.textContent=state.completedDays.has(day.d)?'Completado ✓':'Marcar práctica como completada';b.addEventListener('click',()=>{state.completedDays.add(day.d);b.textContent='Completado ✓'});el.appendChild(b)};
 if(day.interaction==='breathing'){el.innerHTML='<div class="breath">Respira</div><div class="timer">00:50</div><p class="micro">5 ciclos · 4 s inhalar / 6 s exhalar</p><button type="button" class="btn sec">Iniciar</button>';const ball=el.querySelector('.breath'),tm=el.querySelector('.timer'),btn=el.querySelector('button');let t=null,left=50;btn.addEventListener('click',()=>{if(t){clearInterval(t);t=null;btn.textContent='Continuar';return;}btn.textContent='Pausar';t=setInterval(()=>{left--;const phase=(50-left)%10<4;ball.classList.toggle('in',phase);tm.textContent=`00:${String(Math.max(left,0)).padStart(2,'0')}`;if(left<=0){clearInterval(t);t=null;btn.textContent='Repetir';left=50;ball.classList.remove('in')}},1000)});doneBtn();return;}
 if(['arousal','baseline','context','confidence','pelvic','progress','reassessment'].includes(day.interaction)){el.innerHTML='<label class="micro">Registro rápido 0–10</label><div class="rangeRow"><input type="range" min="0" max="10" value="5"><b>5</b></div>';const r=el.querySelector('input'),v=el.querySelector('b');r.addEventListener('input',()=>v.textContent=r.value);doneBtn();return;}
 if(['checklist','steps','planner','priorities','selectBest','ifthen'].includes(day.interaction)){const items=['Me sentí seguro con la práctica','Pude hacerla sin presión excesiva','Entendí qué debía observar','Sé qué ajustar la próxima vez'];el.innerHTML=items.map((x,i)=>`<label style="display:block;margin:8px 0"><input type="checkbox"> ${x}</label>`).join('');doneBtn();return;}
 if(['timer','cycles','selfpractice','profileSkill','ladder'].includes(day.interaction)){el.innerHTML='<div class="timer">05:00</div><button type="button" class="btn sec">Iniciar 5 min</button>';let left=300,t=null;const tm=el.querySelector('.timer'),b=el.querySelector('button');b.addEventListener('click',()=>{if(t){clearInterval(t);t=null;b.textContent='Continuar';return;}b.textContent='Pausar';t=setInterval(()=>{left--;tm.textContent=`${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`;if(left<=0){clearInterval(t);t=null;b.textContent='Finalizado';}},1000)});doneBtn();return;}
 if(day.interaction==='script'||day.interaction==='reframe'){el.innerHTML='<textarea rows="3" style="width:100%;background:#08171b;border:1px solid var(--line);color:white;border-radius:11px;padding:12px" placeholder="Escribe tu versión personal aquí…"></textarea>';doneBtn();return;}
 doneBtn();}
function populateCoachDays(){const s=$('coachDay');if(!s)return;s.innerHTML='';for(let i=1;i<=28;i++){const o=document.createElement('option');o.value=i;o.textContent=`Día ${i}`;s.appendChild(o)}}
function clamp(v){return Math.max(0,Math.min(10,Number(v)||0))}
$('coachSave')?.addEventListener('click',()=>{const rec={day:Number($('coachDay').value),sleep:clamp($('sleep').value),stress:clamp($('stress').value),confidence:clamp($('confidence').value),desire:clamp($('desire').value),outcome:clamp($('outcome').value),activity:$('sexualActivity').value==='1',completed:$('completed').value==='1',flag:$('newFlag').value==='1'};let decision='PROGRESAR',reason='Buena adherencia y respuesta suficiente para avanzar de forma gradual.';if(rec.flag){decision='REVISIÓN CLÍNICA';reason='Apareció una bandera nueva. Prioriza seguridad antes de intensificar el entrenamiento.'}else if(!rec.completed||rec.sleep<=3||rec.stress>=8){decision='BAJAR INTENSIDAD';reason='La carga actual o el contexto puede interferir con el aprendizaje. Simplificamos antes de avanzar.'}else if(rec.outcome<=4||rec.confidence<=4){decision='REPETIR';reason='Conviene consolidar la habilidad actual antes de añadir dificultad.'}state.coach.push({...rec,decision});$('coachDecision').innerHTML=`<div class="notice ${decision==='REVISIÓN CLÍNICA'?'danger':decision==='BAJAR INTENSIDAD'?'warn':'good'}"><b>${decision}</b><br>${reason}</div>`;renderProgress();});
function avg(key){if(!state.coach.length)return null;return state.coach.reduce((a,r)=>a+r[key],0)/state.coach.length}
function renderProgress(){$('stChecks').textContent=state.coach.length;$('stAdh').textContent=state.coach.length?Math.round(state.coach.filter(r=>r.completed).length/state.coach.length*100)+'%':'0%';$('stConf').textContent=avg('confidence')==null?'—':avg('confidence').toFixed(1);$('stOutcome').textContent=avg('outcome')==null?'—':avg('outcome').toFixed(1);$('stDecision').textContent=state.coach.at(-1)?.decision||'—';const chart=$('chart');chart.innerHTML='';state.coach.forEach(r=>{const c=document.createElement('div');c.className='col';c.style.height=`${Math.max(4,r.confidence*10)}%`;c.dataset.v=`D${r.day}: ${r.confidence}/10`;chart.appendChild(c)});}
})();