(()=>{
const route={
1:{title:'Línea de base del control eyaculatorio',learn:'El objetivo no es perseguir un número perfecto de minutos. Para entrenar control necesitamos conocer latencia aproximada cuando sea evaluable, sensación de control, nivel de angustia y satisfacción.',practice:'Registra tu situación reciente: control percibido 0–10, satisfacción 0–10 y, solo si hubo penetración vaginal y deseas medirlo, IELT aproximado. Si no hubo una experiencia pertinente, marca no evaluable.',measure:'Control 0–10, satisfacción 0–10, ansiedad 0–10 e IELT opcional cuando corresponda.',apply:'No provoques una experiencia sexual solo para medir. Usa datos naturales cuando existan.',complete:'Guarda tu línea de base. En la versión clínica, escalas validadas se usarán solo cuando sean aplicables y con permisos adecuados.',tool:'baseline'},
2:{title:'Tu patrón eyaculatorio real',learn:'La eyaculación rápida puede presentarse desde el inicio de la vida sexual o aparecer después; también puede variar según pareja, contexto, ansiedad, frecuencia sexual y presencia de dificultades eréctiles.',practice:'Identifica si el patrón ha sido estable desde siempre o si cambió recientemente; compara autoestimulación y actividad con pareja; registra si la erección se mantiene bien.',measure:'Marca dónde ocurre mayor pérdida de control y qué factores la empeoran o mejoran.',apply:'Observa el patrón sin intentar corregirlo todavía.',complete:'SPM identifica si el entrenamiento puede ser autoguiado o si conviene revisión clínica por cambio adquirido, dolor, síntomas urinarios u otra señal.',tool:'pattern'},
3:{title:'Respiración diafragmática y desaceleración',learn:'La activación autonómica alta y la tensión corporal pueden acelerar la escalada de excitación. Respirar no “detiene” la eyaculación por sí sola, pero puede mejorar autorregulación cuando se combina con entrenamiento.',practice:'Realiza 5 ciclos: inhalar 4 segundos y exhalar 6 segundos, aflojando abdomen, glúteos y periné.',measure:'Tensión corporal antes y después 0–10.',apply:'Usa 2–3 ciclos cuando notes que la excitación sube demasiado rápido.',complete:'Registra cuánto disminuyó la tensión.',tool:'breathing'},
4:{title:'Atención plena sexual: sentir antes de reaccionar',learn:'Mindfulness y entrenamiento atencional pueden ayudar a reconocer sensaciones tempranas sin entrar en ansiedad, juicio o urgencia.',practice:'Durante 5 minutos de autoexploración o imaginación erótica, observa respiración, contacto y excitación sin buscar orgasmo. Cada vez que aparezca “voy a terminar ya”, vuelve a sensaciones concretas.',measure:'Número de veces que apareció urgencia mental y facilidad para volver a la experiencia 0–10.',apply:'Practica esta atención en una experiencia real si ocurre.',complete:'Guarda qué señal corporal reconociste antes que otras veces.',tool:'mindfulness'},
5:{title:'Mapa de aceleradores de la excitación',learn:'Ritmo, presión, posición, ansiedad, largos periodos sin actividad, prisa, fantasía intensa o miedo a perder la erección pueden acelerar la excitación. Conocerlos permite intervenir antes.',practice:'Selecciona tus principales aceleradores y tus principales reguladores.',measure:'Elige los dos factores que más elevan tu excitación rápidamente.',apply:'Modifica un factor controlable en la próxima práctica.',complete:'Guarda tu mapa de aceleradores y reguladores.',tool:'facilitators'},
6:{title:'Piso pélvico inteligente: conciencia y relajación primero',learn:'El piso pélvico participa en el control eyaculatorio, pero fortalecer indiscriminadamente no es la respuesta. La evidencia reciente favorece abordajes combinados y no identifica un protocolo único superior.',practice:'Aprende a identificar el periné y a relajarlo por completo. Si no hay dolor ni tensión, añade contracciones suaves y breves seguidas de relajación más larga. Si hay dolor, hipertonía o dificultad para soltar, evita fortalecimiento y considera fisioterapia especializada.',measure:'Facilidad para relajar 0–10, tensión 0–10 y dolor sí/no.',apply:'Observa si aprietas periné, abdomen o glúteos cuando la excitación aumenta.',complete:'SPM define relajación, coordinación o progresión; nunca Kegels automáticos.',tool:'pelvic'},
8:{title:'Escala de excitación 0–10 y punto de inevitabilidad',learn:'El control mejora cuando reconoces la excitación antes del punto de inevitabilidad. El objetivo no es quedarte siempre “bajo”, sino aprender a subir y bajar voluntariamente.',practice:'Durante una práctica de baja presión, identifica tres zonas: 0–4 baja/moderada, 5–7 entrenable, 8–9 muy alta y cercana al límite. No necesitas llegar al orgasmo.',measure:'Marca en qué nivel suele volverse difícil reducir la excitación.',apply:'Tu meta inicial será intervenir 1–2 puntos antes de ese umbral.',complete:'Guarda tu umbral personal.',tool:'arousal'},
9:{title:'Start–Stop I: aprender a bajar la curva',learn:'La técnica Start–Stop es una de las estrategias conductuales más estudiadas en EP. Su valor está en aprender a reconocer el ascenso de excitación y recuperar control antes de reiniciar.',practice:'En autoestimulación, aumenta excitación hasta una zona aproximada 6–7/10; detén la estimulación 30–60 segundos o hasta bajar 2 puntos; respira y relaja; reinicia. Realiza 3 ciclos. No es obligatorio eyacular al final.',measure:'Nivel al pausar, cuánto bajó y sensación de control 0–10.',apply:'Prioriza calidad del control sobre duración total.',complete:'Registra cuántos ciclos pudiste completar sin entrar en urgencia.',tool:'startstop'},
10:{title:'Control de ritmo e intensidad',learn:'El control eyaculatorio no depende únicamente de detenerse. Aprender a modificar velocidad, presión y patrón de estimulación permite regular sin desconectarse.',practice:'Realiza 3 bloques: ritmo suave, ritmo medio y regreso a suave. Cambia intensidad antes de alcanzar tu zona crítica.',measure:'Control 0–10 y excitación máxima alcanzada.',apply:'Prueba un cambio de ritmo intencional en una situación sexual real cuando corresponda.',complete:'Identifica qué modificación reduce mejor la escalada.',tool:'pacing'},
11:{title:'Reducir ansiedad y pensamiento de catástrofe',learn:'Pensamientos como “ya voy a terminar”, “voy a fallar” o “debo durar X minutos” pueden aumentar vigilancia y tensión. La terapia cognitivo-conductual trabaja esas interpretaciones.',practice:'Detecta una frase de presión y reemplázala por una instrucción funcional: “puedo bajar el ritmo”, “puedo pausar”, “el objetivo es control, no perfección”.',measure:'Presión antes y después 0–10.',apply:'Usa una sola frase funcional durante la próxima práctica.',complete:'Guarda la frase que más disminuye presión.',tool:'reframe'},
12:{title:'Start–Stop II: ciclos más realistas',learn:'La progresión consiste en tolerar más excitación con menos interrupciones, no en eliminar las pausas de golpe.',practice:'Realiza 4 ciclos. En los dos primeros pausa al llegar a 6–7/10. En los dos siguientes intenta regular primero con menor ritmo y respiración; pausa solo si continúas subiendo.',measure:'Número de ciclos regulados sin pausa completa y control 0–10.',apply:'Si el control cae, vuelve al nivel anterior; repetir es parte del entrenamiento.',complete:'El Coach decide progresar, repetir o simplificar.',tool:'startstop2'},
13:{title:'Técnica de compresión: opción, no obligación',learn:'La técnica squeeze/compresión aparece en estudios conductuales históricos y revisiones, pero su evidencia es menos consistente que la de un programa combinado. En SPM se ofrece como variante opcional, no como técnica central.',practice:'Si deseas probarla y no hay dolor ni lesión: cuando la excitación esté alta, detén la estimulación y aplica una presión suave y breve en la zona distal del pene según instrucción educativa, sin dolor. Si incomoda o empeora la respuesta, no la uses.',measure:'¿Disminuyó la excitación? ¿Generó incomodidad? Control 0–10.',apply:'Compárala con Start–Stop y conserva solo la estrategia que te resulte más cómoda y útil.',complete:'Marca útil, neutra o no recomendable para ti.',tool:'squeeze'},
14:{title:'Revisión de Semana 2: control, no solo minutos',learn:'La mejoría se observa en varias dimensiones: mayor control, menor urgencia, menor angustia, más satisfacción y, cuando corresponde, aumento de IELT.',practice:'Revisa tus registros de excitación, Start–Stop, ritmo, ansiedad y piso pélvico.',measure:'Clasifica la semana: progreso claro, parcial, estable o más difícil.',apply:'El Daily Coach decide qué habilidad merece más práctica.',complete:'Actualiza tu prioridad para la transferencia.',tool:'progress'},
15:{title:'Focalización sensorial y reducción de meta',learn:'Sensate Focus puede disminuir presión de rendimiento y ayudar a mantener atención en placer y conexión, en vez de vigilar constantemente el tiempo hasta eyacular.',practice:'10–15 minutos de contacto sensorial sin objetivo obligatorio de penetración u orgasmo. Si hay pareja, ambos deben estar de acuerdo; si no, adapta a autoexploración consciente.',measure:'Presencia, disfrute, presión y sensación de control 0–10.',apply:'Termina antes de convertir la experiencia en una prueba.',complete:'Registra qué tipo de contacto favorece más regulación.',tool:'sensate'},
16:{title:'Reentrenamiento de autoestimulación',learn:'La masturbación puede convertirse en un laboratorio de aprendizaje si se usa para reconocer y modular excitación, no para terminar lo más rápido posible.',practice:'Realiza una sesión lenta de 10–15 minutos con cambios deliberados de ritmo, pausas, respiración y atención a sensaciones. Evita perseguir una duración exacta.',measure:'Cuántas veces pudiste reducir excitación sin perder conexión con el placer.',apply:'Mantén esta forma de práctica varias veces por semana si resulta útil y no compulsiva.',complete:'Registra qué patrón de estimulación te da mayor control.',tool:'masturbation'},
17:{title:'Transferencia a pareja I: Start–Stop compartido',learn:'La habilidad individual necesita transferirse de forma gradual a la intimidad. La pareja puede ayudar a disminuir presión y reconocer señales de pausa sin interpretarlas como fracaso.',practice:'Si existe pareja y ambos desean participar, acuerden una señal de “bajar” o “pausar”. Practiquen 2–3 ciclos de estimulación y regulación sin obligación de penetración.',measure:'Control, presión y comodidad comunicativa 0–10.',apply:'Conserva un ritmo que te permita reconocer tu escala de excitación.',complete:'Registra si la participación de pareja ayudó o aumentó presión.',tool:'partnerStartstop'},
18:{title:'Comunicación para reducir presión',learn:'La EP afecta con frecuencia a ambos miembros de la pareja. Hablar de ritmo, pausas y expectativas puede mejorar cooperación y satisfacción.',practice:'Adapta un guion: “si bajo el ritmo no significa que algo vaya mal”, “quiero que practiquemos sin medirnos”, “avísame si quieres cambiar el ritmo”.',measure:'Comodidad para comunicar 0–10.',apply:'Usa una frase real cuando sea pertinente.',complete:'Registra el efecto sobre presión y conexión.',tool:'scripts'},
19:{title:'Transferencia a pareja II: regular durante mayor excitación',learn:'La progresión combina contacto, ritmo, pausa y atención para sostener control en situaciones más cercanas a la actividad sexual habitual.',practice:'Si corresponde, practica alternar 30–60 segundos de estímulo moderado con periodos breves de menor intensidad. Si existe penetración, no es obligatorio cronometrar cada segundo.',measure:'Control 0–10, excitación máxima y, si es naturalmente evaluable, IELT aproximado.',apply:'Usa pausa completa solo cuando las estrategias de regulación no sean suficientes.',complete:'Compara con la semana anterior.',tool:'partnerPacing'},
20:{title:'Plan para una experiencia sexual',learn:'Privacidad, cansancio, alcohol, largos periodos de abstinencia, conflicto y miedo a perder la erección pueden modificar el control. Preparar el contexto reduce interferencias evitables.',practice:'Diseña un plan breve: momento con menos prisa, comunicación previa, ritmo inicial moderado, técnica principal y una alternativa si la excitación sube rápido.',measure:'Cuántos inhibidores o aceleradores pudiste reducir.',apply:'Úsalo solo si surge una oportunidad real.',complete:'Guarda tu contexto más favorable.',tool:'planner'},
21:{title:'Integrar control eyaculatorio y función eréctil',learn:'En algunos hombres, el miedo a perder la erección lleva a estimularse muy rápido; en otros, la DE/EP coexisten. Las guías recomiendan valorar y tratar primero una disfunción eréctil relevante.',practice:'Revisa si acelerar el ritmo es una estrategia para conservar la erección y si la firmeza disminuye al pausar.',measure:'Control eyaculatorio 0–10 y firmeza/no evaluable.',apply:'Si existe dificultad eréctil persistente, SPM debe activar o priorizar la ruta eréctil y sugerir valoración clínica cuando corresponda.',complete:'Integra ambos dominios en tu mapa si están relacionados.',tool:'dual'},
22:{title:'Consolida tus dos mejores herramientas',learn:'No necesitas usar todas las técnicas para siempre. El objetivo es descubrir qué combinación te da mayor control con menor esfuerzo.',practice:'Elige tus dos mejores estrategias: escala de excitación, cambio de ritmo, Start–Stop, respiración, mindfulness, comunicación, Sensate Focus o piso pélvico si fue indicado.',measure:'Utilidad 0–10 y esfuerzo requerido.',apply:'Integra una de ellas a una experiencia habitual.',complete:'Marca cuáles conservarás después del ciclo.',tool:'best'},
23:{title:'Flexibilidad: dejar de competir contra el cronómetro',learn:'El control eyaculatorio saludable no exige una duración idéntica cada vez. Una meta rígida de minutos puede aumentar presión y reducir satisfacción.',practice:'Transforma una expectativa rígida en una meta funcional: de “debo durar X” a “quiero reconocer mi excitación y poder regularla cuando sea necesario”.',measure:'Presión antes/después 0–10.',apply:'En la próxima experiencia evalúa control y satisfacción, no solo tiempo.',complete:'Guarda tu nueva meta funcional.',tool:'reframe'},
24:{title:'Tu curva de control empieza a verse',learn:'El progreso se observa como tendencia: más percepción de control, menor urgencia, mejor satisfacción, menor angustia y, cuando es pertinente, mayor latencia.',practice:'Revisa tus registros de las últimas tres semanas.',measure:'Marca qué mejoró, qué sigue igual y qué necesita otra estrategia.',apply:'Mantén las herramientas que están funcionando.',complete:'Se inicia la reevaluación final.',tool:'progress'},
25:{title:'Prevención de recaídas',learn:'Estrés, cambios de pareja, menor frecuencia sexual o una experiencia difícil pueden reducir temporalmente el control. Tener un protocolo evita interpretar un episodio aislado como fracaso total.',practice:'Construye tu plan “si ocurre X, haré Y”: volver a escala de excitación, reducir ritmo, repetir Start–Stop, disminuir presión o pedir revisión clínica si el cambio es nuevo y persistente.',measure:'Confianza para recuperarte 0–10.',apply:'Guarda un plan breve y realista.',complete:'Tu protocolo queda listo para mantenimiento.',tool:'ifthen'},
26:{title:'¿Mantenimiento, nuevo ciclo o revisión clínica?',learn:'La continuidad debe depender de tus datos. Una EP adquirida reciente, dolor, síntomas urinarios, cambios hormonales/neurológicos relevantes o una DE importante requieren una mirada clínica más amplia.',practice:'Revisa evolución, adherencia, síntomas nuevos y qué factores siguen limitando el control.',measure:'Elige máximo dos objetivos para el siguiente ciclo.',apply:'Si hay señales clínicas nuevas, prioriza valoración profesional sobre intensificar ejercicios.',complete:'SPM prepara el siguiente paso.',tool:'priorities'},
27:{title:'Ensayo autónomo de control eyaculatorio',learn:'Antes de cerrar el ciclo buscamos comprobar si puedes reconocer tu excitación y elegir una estrategia sin depender de instrucciones paso a paso.',practice:'Realiza una práctica o experiencia usando tu mejor combinación de regulación, ritmo, pausa y atención.',measure:'Control, presión, satisfacción y autonomía 0–10; IELT solo si fue naturalmente evaluable.',apply:'Adáptala a tu vida real.',complete:'Registra qué necesitas para mantener el avance.',tool:'autonomous'},
28:{title:'Reevaluación de control eyaculatorio',learn:'El resultado del ciclo no se decide por una sola relación sexual. Se compara línea de base con control percibido, angustia, satisfacción, confianza y latencia cuando es aplicable.',practice:'Completa la reevaluación SPM. En la versión clínica/comercial, PEDT o PEP se incorporarán solo con versión validada, ventana temporal correcta y revisión de permisos.',measure:'Compara inicio vs. final en control, presión, satisfacción, confianza e IELT cuando corresponda.',apply:'SPM propone mantenimiento, nuevo ciclo personalizado o revisión clínica según evolución y seguridad.',complete:'Cierra el ciclo con tu Performance Map actualizado.',tool:'progress'}
};
function isEP(){const t=(document.getElementById('profileTitle')?.textContent||'').toLowerCase();return t.includes('eyaculator')||t.includes('ejaculatory');}
function slider(label,min=0,max=10,val=5){return `<label class="micro">${label}</label><div class="rangeRow"><input type="range" min="${min}" max="${max}" value="${val}"><b>${val}</b></div>`;}
function bind(root){root.querySelectorAll('.rangeRow').forEach(r=>{const i=r.querySelector('input'),b=r.querySelector('b');if(i&&b)i.addEventListener('input',()=>b.textContent=i.value);});}
function toolHtml(type){
 if(type==='baseline')return `<div class="epTool"><b class="tag">Línea de base EP</b>${slider('Control percibido 0–10')}${slider('Satisfacción 0–10')}<label class="micro">IELT aproximado (opcional)</label><select><option>No evaluable</option><option>&lt; 1 minuto</option><option>1–2 minutos</option><option>2–5 minutos</option><option>&gt; 5 minutos</option></select></div>`;
 if(type==='pattern')return `<div class="epTool"><b class="tag">Patrón</b><label><input type="radio" name="epPattern"> Desde el inicio de mi vida sexual</label><br><label><input type="radio" name="epPattern"> Apareció después</label><br><label><input type="radio" name="epPattern"> Variable / situacional</label></div>`;
 if(type==='breathing')return `<div class="epTool">${slider('Tensión antes 0–10')}${slider('Tensión después 0–10')}</div>`;
 if(type==='mindfulness')return `<div class="epTool"><b class="tag">Atención plena</b>${slider('Facilidad para volver a sensaciones 0–10')}</div>`;
 if(type==='facilitators')return `<div class="epTool"><b class="tag">Aceleradores</b><label><input type="checkbox"> Ritmo muy rápido</label><br><label><input type="checkbox"> Presión por durar</label><br><label><input type="checkbox"> Miedo a perder la erección</label><br><label><input type="checkbox"> Prisa / poca privacidad</label><br><label><input type="checkbox"> Tensión corporal</label></div>`;
 if(type==='pelvic')return `<div class="epTool"><b class="tag">Piso pélvico</b>${slider('Facilidad para relajar 0–10')}<label><input type="checkbox"> Dolor o tensión marcada</label></div>`;
 if(type==='arousal')return `<div class="epTool">${slider('Mi umbral de pérdida de control 0–10',0,10,7)}</div>`;
 if(type==='startstop'||type==='startstop2')return `<div class="epTool"><b class="tag">Start–Stop guiado</b><div class="timer">Ciclo 1 / 3</div>${slider('Excitación actual 0–10',0,10,5)}<button type="button" class="btn sec sm epCycle">Registrar pausa / siguiente ciclo</button></div>`;
 if(type==='pacing')return `<div class="epTool"><b class="tag">Control de ritmo</b><select><option>Ritmo suave</option><option>Ritmo medio</option><option>Reducir intensidad</option><option>Pausa breve</option></select>${slider('Control 0–10')}</div>`;
 if(type==='reframe')return `<div class="epTool"><b class="tag">Reencuadre</b><input type="text" placeholder="Pensamiento de presión"><input type="text" placeholder="Instrucción funcional"></div>`;
 if(type==='squeeze')return `<div class="epTool"><b class="tag">Variante opcional</b><p class="micro">No debe causar dolor. Si incomoda, no se utiliza.</p>${slider('Utilidad 0–10')}</div>`;
 if(type==='sensate')return `<div class="epTool"><b class="tag">Sensate Focus</b><label><input type="checkbox"> Sin meta de penetración</label><br><label><input type="checkbox"> Sin obligación de orgasmo</label>${slider('Presión 0–10')}</div>`;
 if(type==='masturbation')return `<div class="epTool"><b class="tag">Práctica de autoestimulación</b><select><option>Ritmo lento</option><option>Cambio de intensidad</option><option>Pausa</option><option>Respiración / relajación</option></select>${slider('Control 0–10')}</div>`;
 if(type==='partnerStartstop'||type==='partnerPacing')return `<div class="epTool"><b class="tag">Transferencia con pareja</b>${slider('Control 0–10')}${slider('Presión 0–10')}</div>`;
 if(type==='scripts')return `<div class="epTool"><button type="button" class="btn sec sm">Quiero bajar el ritmo</button> <button type="button" class="btn sec sm">Paremos un momento</button> <button type="button" class="btn sec sm">Sin medirnos hoy</button></div>`;
 if(type==='planner')return `<div class="epTool"><textarea rows="2" placeholder="Mi contexto y estrategia para la próxima experiencia..."></textarea></div>`;
 if(type==='dual')return `<div class="epTool">${slider('Control eyaculatorio 0–10')}<label class="micro">Firmeza</label><select><option>No evaluable</option><option>Baja</option><option>Intermedia</option><option>Buena</option></select></div>`;
 if(type==='best')return `<div class="epTool"><input type="text" placeholder="Herramienta 1"><input type="text" placeholder="Herramienta 2"></div>`;
 if(['progress','ifthen','priorities','autonomous'].includes(type))return `<div class="epTool">${slider('Control actual 0–10')}${slider('Satisfacción actual 0–10')}${slider('Presión actual 0–10')}</div>`;
 return '';
}
function enhanceCard(card,spec){if(card.dataset.epRoute==='1')return;card.dataset.epRoute='1';const h=card.querySelector('.dayTop h4');if(h)h.textContent=spec.title;const summary=card.querySelector('.dayTop p');if(summary)summary.textContent=spec.learn.slice(0,105)+'…';const ps=card.querySelectorAll('.lesson p');[spec.learn,spec.practice,spec.measure,spec.apply,spec.complete].forEach((v,i)=>{if(ps[i])ps[i].textContent=v;});const chips=card.querySelector('.moduleMeta');if(chips){const c=document.createElement('span');c.className='chip';c.textContent='Ruta específica de control eyaculatorio';chips.appendChild(c);}const inter=card.querySelector('.interactive');if(inter&&!inter.querySelector('.epTool')){const box=document.createElement('div');box.innerHTML=toolHtml(spec.tool);if(box.firstElementChild){inter.prepend(box.firstElementChild);bind(inter);const cyc=inter.querySelector('.epCycle');if(cyc){let n=1;cyc.addEventListener('click',()=>{n=Math.min(n+1,spec.tool==='startstop2'?4:3);const tm=inter.querySelector('.timer');if(tm)tm.textContent=`Ciclo ${n} / ${spec.tool==='startstop2'?4:3}`;});}}}}
function enhance(){if(!isEP())return;const intro=document.getElementById('weekIntro');if(intro&&!intro.dataset.epRoute){intro.dataset.epRoute='1';intro.insertAdjacentHTML('beforeend','<div class="micro" style="margin-top:8px">Ruta EP: conciencia de excitación, Start–Stop progresivo, regulación de ritmo, mindfulness, piso pélvico selectivo, transferencia a pareja y seguimiento de control/satisfacción. La evidencia conductual es útil pero heterogénea; SPM evita promesas de curación.</div>');}document.querySelectorAll('.dayCard').forEach(card=>{const d=Number(card.querySelector('.dayNum')?.textContent);if(route[d])enhanceCard(card,route[d]);});const sub=document.getElementById('coachSub');if(sub&&!document.getElementById('epCoachNote'))sub.insertAdjacentHTML('afterend','<p class="micro" id="epCoachNote">En EP el Coach prioriza control percibido, excitación, presión, satisfacción y adherencia. IELT se solicita solo cuando una experiencia pertinente ocurrió de forma natural.</p>');}
let queued=false;const schedule=()=>{if(queued)return;queued=true;setTimeout(()=>{queued=false;enhance();},0);};new MutationObserver(schedule).observe(document.body,{subtree:true,childList:true,characterData:true});document.addEventListener('click',schedule);setTimeout(enhance,50);
})();