(()=>{
'use strict';

const PROGRAM_INTRO=`Bienvenido a tu Programa de Entrenamiento de Control Eyaculatorio. Durante las próximas cuatro semanas realizarás un entrenamiento progresivo diseñado para ayudarte a reconocer con mayor anticipación cómo aumenta tu nivel de excitación y desarrollar una mejor capacidad para regularlo antes de alcanzar el punto de no retorno eyaculatorio. Realizarás tres sesiones por semana. No necesitas añadir entrenamientos adicionales: SPM te indicará qué ejercicio corresponde en cada sesión y cuándo avanzar al siguiente nivel. Durante la primera semana repetiremos una misma técnica en las tres sesiones. Esta repetición es intencional. Antes de incorporar nuevas variantes necesitamos que aprendas a reconocer las señales de tu cuerpo, identificar con mayor precisión tu nivel de excitación y anticipar el momento adecuado para realizar una parada. Por eso, cuando regreses a tu segunda o tercera sesión podrás encontrar nuevamente el mismo ejercicio. Esto no significa que tu programa no esté avanzando. Cada sesión tiene como objetivo mejorar tu reconocimiento y tu control. En las semanas siguientes incorporaremos progresivamente otras estrategias. Finalmente, durante la cuarta semana volveremos a trabajar las diferentes técnicas aprendidas para ayudarte a integrarlas y reconocer cuál utilizar según tu respuesta. No necesitas hacerlo perfecto desde el comienzo. SPM te irá guiando sesión a sesión. Cuando estés listo, comienza tu primera semana de entrenamiento.`;

const TECH={
 startstop:{
  name:'Start/Stop',accent:'#0b6f94',soft:'#e7f3f8',
  intro:`Bienvenido al entrenamiento Start Stop. Esta técnica está diseñada para ayudarte a reconocer con mayor anticipación el aumento de tu excitación y las sensaciones que aparecen antes de alcanzar el punto de no retorno eyaculatorio. A través de la práctica aprenderás a detener la estimulación en el momento adecuado, permitir que la excitación disminuya y posteriormente reiniciar. Trabajaremos alrededor de un nivel de excitación de ocho sobre diez, intentando anticiparnos antes de que la eyaculación se vuelva inevitable. La meta de cuatro a seis paradas por sesión es progresiva. No esperamos que la consigas desde las primeras sesiones. Reconocer correctamente una sola parada ya es parte del progreso. Esta técnica forma parte de las tres sesiones semanales programadas por SPM; no necesitas añadir sesiones adicionales por tu cuenta.`,
  steps:[
   ['01','Prepárate','Elige un momento tranquilo y sin prisa. El objetivo es entrenar reconocimiento y control, no evaluar tu rendimiento.'],
   ['02','Inicia gradualmente','Comienza la autoestimulación a una intensidad cómoda y observa cómo aumenta tu excitación.'],
   ['03','Reconoce el umbral','Usa la escala de 0 a 10. Cuando te aproximes a 8/10, anticípate: no esperes al punto de no retorno.'],
   ['04','STOP','Detén completamente la estimulación. Mantén respiración natural y observa cómo disminuye la excitación.'],
   ['05','Espera el descenso','Reinicia solo cuando percibas una reducción clara de la excitación y recuperes sensación de control.'],
   ['06','Reinicia y repite','Vuelve a estimular de forma gradual. Progresa hacia 4–6 paradas antes de la eyaculación.']
  ]
 },
 squeeze:{
  name:'Stop–Squeeze',accent:'#6d56a8',soft:'#f0ecfa',
  intro:`Bienvenido al entrenamiento Stop Squeeze. Esta variante utiliza el mismo principio de anticipación del aumento de la excitación, pero añade una compresión suave y breve cuando realizas la parada. El objetivo sigue siendo reconocer las señales previas al punto de no retorno y actuar alrededor de un nivel de excitación de ocho sobre diez. Cuando detengas la estimulación, realiza una compresión suave durante cinco a diez segundos, sin dolor, sin fuerza excesiva y sin buscar perder por completo la excitación. Después permite que la excitación disminuya antes de reiniciar. La meta de cuatro a seis paradas es progresiva y no debe interpretarse como una exigencia desde las primeras sesiones. Esta técnica forma parte de las tres sesiones semanales indicadas por SPM; no debes sumarla a Start Stop como un entrenamiento adicional.`,
  steps:[
   ['01','Prepárate','Realiza el entrenamiento en un momento tranquilo. La meta es practicar anticipación, no alcanzar un resultado perfecto.'],
   ['02','Aumenta gradualmente','Inicia la autoestimulación y observa el ascenso de tu excitación sin acelerar deliberadamente el ritmo.'],
   ['03','Anticípate cerca de 8/10','Cuando reconozcas que te aproximas a 8/10, detén la estimulación antes del punto de no retorno.'],
   ['04','Compresión suave','Realiza una compresión suave durante 5–10 segundos. Nunca debe producir dolor, irritación ni requerir fuerza.'],
   ['05','Permite el descenso','Espera a que la excitación disminuya de forma clara, manteniendo respiración natural y sin apresurarte.'],
   ['06','Reinicia','Retoma gradualmente y repite según tu capacidad. Una primera parada correctamente anticipada ya cuenta como progreso.']
  ]
 },
 combined:{
  name:'Técnica combinada',accent:'#27816b',soft:'#e8f5f1',
  intro:`Bienvenido a la fase de integración. En esta etapa utilizarás lo aprendido con Start Stop y Stop Squeeze dentro de una misma sesión. La finalidad no es mezclar técnicas de forma automática, sino aprender a decidir qué recurso utilizar según tu nivel de excitación y tu capacidad de recuperación. Cuando te aproximes a ocho sobre diez, la primera opción será detener la estimulación y observar el descenso. Si necesitas una ayuda adicional y la técnica ya te resulta cómoda, puedes incorporar una compresión suave durante cinco a diez segundos. Mantén el objetivo progresivo de cuatro a seis paradas, sin convertirlo en una exigencia. SPM mantiene un máximo de tres sesiones semanales de control eyaculatorio: esta sesión sustituye una de ellas, no se suma como una práctica adicional.`,
  steps:[
   ['01','Reconoce primero','Inicia gradualmente y presta atención a tus señales corporales y al ascenso de la excitación.'],
   ['02','Anticípate','Al acercarte a 8/10, detén la estimulación antes del punto de no retorno.'],
   ['03','Elige el recurso','Si la excitación desciende con la pausa, utiliza Start/Stop. Si necesitas apoyo adicional, puedes añadir una compresión suave.'],
   ['04','Si usas Squeeze','Mantén una compresión suave durante 5–10 segundos, nunca dolorosa ni excesiva.'],
   ['05','Espera recuperación','Permite un descenso claro de la excitación antes de reiniciar.'],
   ['06','Integra y repite','Alterna solo cuando sea útil. El objetivo es aprender a regular, no acumular técnicas ni aumentar la frecuencia.']
  ]
 }
};

const SCHEDULE={
 1:{week:1,session:1,tech:'startstop'},3:{week:1,session:2,tech:'startstop'},5:{week:1,session:3,tech:'startstop'},
 8:{week:2,session:1,tech:'squeeze'},10:{week:2,session:2,tech:'squeeze'},12:{week:2,session:3,tech:'squeeze'},
 15:{week:3,session:1,tech:'combined'},17:{week:3,session:2,tech:'combined'},19:{week:3,session:3,tech:'combined'},
 22:{week:4,session:1,tech:'startstop'},24:{week:4,session:2,tech:'squeeze'},26:{week:4,session:3,tech:'combined'}
};

const WEEK_LABELS={1:['RECONOCER','Start/Stop · 3 sesiones'],2:['PROGRESAR','Stop–Squeeze · 3 sesiones'],3:['INTEGRAR','Técnica combinada · 3 sesiones'],4:['CONSOLIDAR','1 Start/Stop + 1 Stop–Squeeze + 1 combinada']};

const css=`
#spmEcModal{position:fixed;inset:0;z-index:1000;background:rgba(4,12,18,.84);backdrop-filter:blur(8px);display:none;overflow:auto;padding:22px}#spmEcModal.on{display:block}
.ecShell{width:min(1080px,100%);margin:18px auto;background:#f7fafc;color:#0c2230;border-radius:24px;overflow:hidden;box-shadow:0 30px 90px rgba(0,0,0,.4)}
.ecHead{background:#071b27;color:#fff;padding:22px 28px;display:flex;align-items:center;justify-content:space-between;gap:16px}.ecHead small{display:block;color:#8fb7c8;text-transform:uppercase;letter-spacing:.12em;font-weight:800}.ecHead h2{margin:4px 0 0;font-size:27px}.ecClose{border:1px solid rgba(255,255,255,.18);background:transparent;color:#fff;border-radius:12px;padding:9px 12px;cursor:pointer}.ecBody{padding:26px}
.ecCard{background:#fff;border:1px solid #dbe7ed;border-radius:18px;padding:20px}.ecIntroGrid{display:grid;grid-template-columns:1.1fr .9fr;gap:18px}.ecAudio{display:flex;gap:12px;align-items:center}.ecAudioIcon{width:52px;height:52px;border-radius:50%;display:grid;place-items:center;background:#0b5d7b;color:#fff;font-size:23px}.ecAudioText b{display:block;font-size:17px}.ecAudioText span{font-size:13px;color:#5e7480}.ecProgress{height:7px;background:#dfe9ee;border-radius:20px;overflow:hidden;margin:16px 0}.ecProgress i{display:block;height:100%;width:0;background:#0b6f94;transition:width .3s}.ecActions{display:flex;gap:10px;flex-wrap:wrap}.ecBtn{border:0;border-radius:12px;padding:12px 16px;font-weight:800;cursor:pointer}.ecBtn.pri{background:#0b6687;color:#fff}.ecBtn.sec{background:#e8f1f5;color:#153747}.ecBtn:disabled{opacity:.4;cursor:not-allowed}.ecNote{background:#eef7fb;border-left:4px solid #1682aa;border-radius:12px;padding:13px;font-size:14px;line-height:1.45}.ecRoadmap{display:grid;gap:9px;margin-top:14px}.ecWeek{border:1px solid #dbe7ed;border-radius:13px;padding:12px;display:grid;grid-template-columns:42px 1fr auto;gap:10px;align-items:center}.ecWeek .n{width:36px;height:36px;border-radius:10px;background:#edf4f7;display:grid;place-items:center;font-weight:900}.ecWeek b{display:block}.ecWeek span{font-size:12px;color:#637983}.ecWeek.current{border-color:#5e9eb7;background:#f3fbfe}.ecWeek.future{opacity:.65}.ecBadge{font-size:11px!important;font-weight:900;padding:5px 8px;border-radius:20px;background:#eaf2f5;color:#34515f!important}
.ecTeach,.ecPractice{display:none}.ecTeach.on,.ecPractice.on{display:block}.ecScale{display:flex;gap:4px;margin:14px 0}.ecScale span{flex:1;text-align:center;padding:9px 2px;background:#e9f1f4;border-radius:8px;font-size:12px;font-weight:800}.ecScale span.hot{background:#ffe8c8;color:#7d4700}.ecSteps{display:grid;gap:9px;margin-top:14px}.ecStep{display:grid;grid-template-columns:44px 1fr;gap:11px;align-items:start;border:1px solid #dbe7ed;border-radius:14px;padding:13px;background:#fff}.ecStep .num{width:36px;height:36px;border-radius:10px;display:grid;place-items:center;font-weight:900}.ecStep h4{margin:0 0 4px}.ecStep p{margin:0;color:#526b77;line-height:1.45}.ecPracticeGrid{display:grid;grid-template-columns:1fr .8fr;gap:18px}.ecTimer{font-size:54px;font-weight:900;letter-spacing:-2px;margin:8px 0}.ecCounter{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:14px 0}.ecMetric{background:#f0f6f8;border-radius:14px;padding:13px}.ecMetric b{font-size:23px;display:block}.ecMetric span{font-size:12px;color:#617783}.ecSlider{width:100%}.ecStops{display:flex;gap:6px;flex-wrap:wrap;margin:12px 0}.ecStopDot{width:34px;height:34px;border-radius:50%;display:grid;place-items:center;background:#e7eef1;font-weight:900}.ecStopDot.on{background:#0b6687;color:white}.ecSqueezeTimer{font-size:38px;font-weight:900;margin:8px 0;color:#6d56a8}.ecSessionMsg{margin-top:12px}.ecFooter{margin-top:18px;padding-top:15px;border-top:1px solid #dce7ec;color:#607783;font-size:12px}.ecLaunch{margin-top:9px;width:100%;background:linear-gradient(135deg,#0d6686,#0b829c)!important;color:white!important;border:0!important}
@media(max-width:760px){#spmEcModal{padding:7px}.ecShell{margin:3px auto;border-radius:18px}.ecBody{padding:16px}.ecIntroGrid,.ecPracticeGrid{grid-template-columns:1fr}.ecHead{padding:17px}.ecHead h2{font-size:21px}.ecTimer{font-size:44px}.ecCounter{grid-template-columns:1fr 1fr}.ecWeek{grid-template-columns:38px 1fr}}
`;

let currentDay=1,currentMeta=SCHEDULE[1],tech=TECH.startstop,utterance=null,progressTimer=null,timerId=null,elapsed=0,running=false,stops=0,squeezeInterval=null,squeezeLeft=0;
const $=id=>document.getElementById(id);

function speak(text,onEnd){stopSpeech();const bar=$('ecAudioProgress'),state=$('ecAudioState'),begin=$('ecBegin');if(bar)bar.style.width='0%';if(begin)begin.disabled=true;if(state)state.textContent='Reproduciendo audio…';if(!('speechSynthesis'in window)){if(state)state.textContent='Tu navegador no permite reproducir el audio. Puedes continuar.';if(begin)begin.disabled=false;if(bar)bar.style.width='100%';return}
 utterance=new SpeechSynthesisUtterance(text);utterance.lang='es-CO';utterance.rate=.94;const voices=speechSynthesis.getVoices();const es=voices.find(v=>/es[-_]CO/i.test(v.lang))||voices.find(v=>/^es/i.test(v.lang));if(es)utterance.voice=es;const estimate=Math.max(35,text.split(/\s+/).length/2.3),start=Date.now();progressTimer=setInterval(()=>{if(bar)bar.style.width=Math.min(96,((Date.now()-start)/1000)/estimate*100)+'%'},300);utterance.onend=()=>{clearInterval(progressTimer);if(bar)bar.style.width='100%';if(state)state.textContent='Audio finalizado. Ya puedes continuar.';if(begin)begin.disabled=false;if(onEnd)onEnd()};utterance.onerror=()=>{clearInterval(progressTimer);if(bar)bar.style.width='100%';if(state)state.textContent='No fue posible completar el audio. Puedes volver a intentarlo o continuar.';if(begin)begin.disabled=false};speechSynthesis.speak(utterance);
}
function stopSpeech(){if('speechSynthesis'in window)speechSynthesis.cancel();clearInterval(progressTimer);progressTimer=null}
function fmt(s){const m=Math.floor(s/60),x=s%60;return String(m).padStart(2,'0')+':'+String(x).padStart(2,'0')}
function startTimer(){if(running)return;running=true;$('ecTimerBtn').textContent='Pausar';timerId=setInterval(()=>{elapsed++;$('ecTimer').textContent=fmt(elapsed)},1000)}
function pauseTimer(){running=false;clearInterval(timerId);timerId=null;if($('ecTimerBtn'))$('ecTimerBtn').textContent='Continuar'}
function toggleTimer(){running?pauseTimer():startTimer()}
function resetPractice(){pauseTimer();elapsed=0;stops=0;squeezeLeft=0;if($('ecTimer'))$('ecTimer').textContent='00:00';renderStops();if($('ecSqueezeBox'))$('ecSqueezeBox').hidden=true;if($('ecSessionMsg'))$('ecSessionMsg').textContent='Tu objetivo es progresivo. Una parada bien anticipada ya cuenta como progreso.'}
function renderStops(){if(!$('ecStops'))return;$('ecStops').innerHTML=[1,2,3,4,5,6].map(n=>`<div class="ecStopDot ${n<=stops?'on':''}">${n}</div>`).join('');$('ecStopCount').textContent=stops}
function registerStop(){if(stops<6)stops++;renderStops();const level=Number($('ecArousal').value);$('ecArousalValue').textContent=level+'/10';$('ecSessionMsg').textContent=`Parada ${stops} registrada ✓. ${stops<4?'El progreso no depende de llegar hoy a 4–6; sigue priorizando anticipación y reconocimiento.':'Ya alcanzaste el rango progresivo de la sesión. No necesitas forzar más repeticiones.'}`;if(tech===TECH.squeeze||tech===TECH.combined)startSqueezeCountdown()}
function startSqueezeCountdown(){clearInterval(squeezeInterval);const box=$('ecSqueezeBox');if(!box)return;box.hidden=false;squeezeLeft=8;$('ecSqueezeTimer').textContent=squeezeLeft+' s';squeezeInterval=setInterval(()=>{squeezeLeft--;$('ecSqueezeTimer').textContent=Math.max(0,squeezeLeft)+' s';if(squeezeLeft<=0){clearInterval(squeezeInterval);$('ecSqueezeTimer').textContent='Finalizado ✓'}},1000)}
function finishPractice(){pauseTimer();clearInterval(squeezeInterval);const rec={day:currentDay,week:currentMeta.week,session:currentMeta.session,tech:currentMeta.tech,stops,seconds:elapsed,arousal:Number($('ecArousal').value),date:new Date().toISOString()};let rows=[];try{rows=JSON.parse(localStorage.getItem('spm_ec_sessions')||'[]')}catch(e){}rows.push(rec);localStorage.setItem('spm_ec_sessions',JSON.stringify(rows.slice(-40)));localStorage.setItem('spm_ec_last_day',String(currentDay));$('ecSessionMsg').innerHTML=`<b>Sesión ${currentMeta.session} de 3 completada ✓</b><br>${nextMessage()}`;const card=[...document.querySelectorAll('.dayCard')].find(c=>Number(c.querySelector('.dayNum')?.textContent||0)===currentDay);const done=card?.querySelector('.doneBtn');if(done&&!/Completado/i.test(done.textContent))done.click()}
function nextMessage(){if(currentMeta.week===1&&currentMeta.session<3)return 'Tu próxima sesión continuará con Start/Stop. La repetición de esta primera semana es intencional: estamos consolidando reconocimiento y anticipación antes de avanzar.';if(currentMeta.week===1)return 'Has completado la fase de reconocimiento. En la próxima semana SPM incorporará Stop–Squeeze.';if(currentMeta.week===2&&currentMeta.session<3)return 'Continuaremos con Stop–Squeeze para consolidar esta variación antes de integrar técnicas.';if(currentMeta.week===2)return 'Has completado la fase de progresión. La próxima semana integraremos ambas estrategias.';if(currentMeta.week===3&&currentMeta.session<3)return 'Continuaremos con la técnica combinada para practicar la elección del recurso según tu respuesta.';if(currentMeta.week===3)return 'Has completado la fase de integración. En la cuarta semana haremos una ronda de las tres estrategias.';if(currentMeta.week===4&&currentMeta.session<3)return 'La próxima sesión de consolidación utilizará otra de las técnicas aprendidas.';return 'Has completado la ronda de consolidación del programa de control eyaculatorio. Tus registros quedarán disponibles para la reevaluación del ciclo de 28 días.'}

function roadmapHtml(){return [1,2,3,4].map(w=>{const cur=w===currentMeta.week, future=w>currentMeta.week;return `<div class="ecWeek ${cur?'current':future?'future':''}"><div class="n">${w}</div><div><b>Semana ${w} · ${WEEK_LABELS[w][0]}</b><span>${WEEK_LABELS[w][1]}</span></div><span class="ecBadge">${cur?'EN CURSO':future?'BLOQUEADA':'APRENDIDA'}</span></div>`}).join('')}
function stepsHtml(){return tech.steps.map(s=>`<div class="ecStep"><div class="num" style="background:${tech.soft};color:${tech.accent}">${s[0]}</div><div><h4>${s[1]}</h4><p>${s[2]}</p></div></div>`).join('')}

function mount(){if($('spmEcModal'))return;const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);const m=document.createElement('div');m.id='spmEcModal';m.innerHTML=`<div class="ecShell" role="dialog" aria-modal="true"><div class="ecHead"><div><small>SPM · Programa de control eyaculatorio</small><h2 id="ecTitle">Entrenamiento progresivo · 28 días</h2></div><button class="ecClose">Cerrar ×</button></div><div class="ecBody">
<section id="ecProgram"><div class="ecIntroGrid"><div class="ecCard"><div class="ecAudio"><div class="ecAudioIcon">🔊</div><div class="ecAudioText"><b>Antes de comenzar, escucha cómo funcionará tu programa</b><span>Cuatro semanas · tres sesiones por semana · progresión guiada por SPM</span></div></div><div class="ecProgress"><i id="ecAudioProgress"></i></div><div id="ecAudioState" class="ecNote">La repetición de la primera semana es intencional. Verás desde el inicio las etapas que iremos desbloqueando.</div><div class="ecActions" style="margin-top:14px"><button class="ecBtn sec" id="ecReplay">🔊 Volver a escuchar</button><button class="ecBtn pri" id="ecBegin" disabled>▶ Comenzar programa</button></div></div><aside class="ecCard"><b>Tu ruta de 4 semanas</b><div class="ecRoadmap" id="ecRoadmap"></div><div class="ecNote" style="margin-top:13px">SPM programa <b>3 sesiones semanales en total</b>. Las variantes no se suman entre sí ni deben convertirse en entrenamiento diario.</div></aside></div></section>
<section id="ecTeach" class="ecTeach"><div class="ecCard"><small id="ecWeekKicker" style="font-weight:900;text-transform:uppercase;letter-spacing:.08em"></small><h3 id="ecTechTitle" style="margin:6px 0"></h3><div class="ecAudio"><div class="ecAudioIcon" id="ecTechIcon">🔊</div><div class="ecAudioText"><b>Introducción de esta técnica</b><span id="ecTechSub"></span></div></div><div class="ecActions" style="margin:12px 0"><button class="ecBtn sec" id="ecTechAudio">🔊 Escuchar introducción</button></div><div class="ecScale">${[0,1,2,3,4,5,6,7,8,9,10].map(n=>`<span class="${n===8?'hot':''}">${n}</span>`).join('')}</div><div class="ecSteps" id="ecSteps"></div><div class="ecActions" style="margin-top:17px"><button class="ecBtn sec" id="ecBackProgram">← Ver ruta</button><button class="ecBtn pri" id="ecGoPractice">Ir a práctica guiada →</button></div><div class="ecFooter">Entrenamiento educativo para adultos. Detén la práctica si aparece dolor, irritación o malestar importante.</div></div></section>
<section id="ecPractice" class="ecPractice"><div class="ecPracticeGrid"><div class="ecCard"><small style="font-weight:900;text-transform:uppercase;letter-spacing:.08em" id="ecPracticeKicker"></small><h3 id="ecPracticeTitle"></h3><div class="ecTimer" id="ecTimer">00:00</div><div class="ecActions"><button class="ecBtn pri" id="ecTimerBtn">Iniciar</button><button class="ecBtn sec" id="ecReset">Reiniciar</button></div><div style="margin-top:18px"><b>Nivel de excitación actual</b><input class="ecSlider" id="ecArousal" type="range" min="0" max="10" value="5"><div class="ecNote">Actual: <b id="ecArousalValue">5/10</b> · Anticípate alrededor de <b>8/10</b>, antes del punto de no retorno.</div></div><div class="ecStops" id="ecStops"></div><button class="ecBtn pri" id="ecRegisterStop">Registrar parada ✓</button><div id="ecSqueezeBox" class="ecNote" style="margin-top:12px" hidden><b>Compresión suave</b><div class="ecSqueezeTimer" id="ecSqueezeTimer">8 s</div><span>Referencia guiada dentro del rango de 5–10 s. Sin dolor ni fuerza excesiva.</span></div></div><aside class="ecCard"><b>Registro de esta sesión</b><div class="ecCounter"><div class="ecMetric"><b id="ecStopCount">0</b><span>paradas registradas</span></div><div class="ecMetric"><b>4–6</b><span>meta progresiva, no exigencia</span></div><div class="ecMetric"><b>3×</b><span>sesiones semanales totales</span></div></div><div class="ecNote ecSessionMsg" id="ecSessionMsg">Tu objetivo es progresivo. Una parada bien anticipada ya cuenta como progreso.</div><div class="ecActions" style="margin-top:15px"><button class="ecBtn pri" id="ecFinish">Finalizar y guardar sesión</button><button class="ecBtn sec" id="ecBackTeach">← Revisar técnica</button></div><div class="ecFooter">No añadas sesiones extra por tu cuenta para “acelerar” el proceso. La recuperación entre sesiones también forma parte del entrenamiento.</div></aside></div></section>
</div></div>`;document.body.appendChild(m);m.querySelector('.ecClose').onclick=close;m.onclick=e=>{if(e.target===m)close()};$('ecReplay').onclick=()=>speak(PROGRAM_INTRO);$('ecBegin').onclick=showTeach;$('ecBackProgram').onclick=showProgram;$('ecTechAudio').onclick=()=>speak(tech.intro);$('ecGoPractice').onclick=showPractice;$('ecBackTeach').onclick=showTeach;$('ecTimerBtn').onclick=toggleTimer;$('ecReset').onclick=resetPractice;$('ecRegisterStop').onclick=registerStop;$('ecFinish').onclick=finishPractice;$('ecArousal').oninput=e=>$('ecArousalValue').textContent=e.target.value+'/10';document.addEventListener('keydown',e=>{if(e.key==='Escape')close()})}
function fill(){tech=TECH[currentMeta.tech];$('ecRoadmap').innerHTML=roadmapHtml();$('ecWeekKicker').textContent=`Semana ${currentMeta.week} · Sesión ${currentMeta.session} de 3`;$('ecWeekKicker').style.color=tech.accent;$('ecTechTitle').textContent=tech.name;$('ecTechSub').textContent=currentMeta.week===1?'Esta semana repetiremos esta misma técnica de forma intencional.':'SPM te indica esta variante como parte de tu progresión semanal.';$('ecSteps').innerHTML=stepsHtml();$('ecPracticeKicker').textContent=`Semana ${currentMeta.week} · Sesión ${currentMeta.session} de 3`;$('ecPracticeKicker').style.color=tech.accent;$('ecPracticeTitle').textContent='Práctica guiada · '+tech.name;$('ecRegisterStop').style.background=tech.accent;$('ecTimerBtn').style.background=tech.accent;resetPractice()}
function showProgram(){stopSpeech();$('ecProgram').style.display='block';$('ecTeach').classList.remove('on');$('ecPractice').classList.remove('on');$('ecTitle').textContent='Entrenamiento progresivo · 28 días'}
function showTeach(){stopSpeech();$('ecProgram').style.display='none';$('ecPractice').classList.remove('on');$('ecTeach').classList.add('on');$('ecTitle').textContent=`Semana ${currentMeta.week} · ${tech.name}`}
function showPractice(){stopSpeech();$('ecProgram').style.display='none';$('ecTeach').classList.remove('on');$('ecPractice').classList.add('on');$('ecTitle').textContent=`Práctica guiada · ${tech.name}`}
function open(day){mount();currentDay=Number(day);currentMeta=SCHEDULE[currentDay]||SCHEDULE[1];fill();$('spmEcModal').classList.add('on');document.body.style.overflow='hidden';showProgram();speak(PROGRAM_INTRO)}
function close(){stopSpeech();pauseTimer();clearInterval(squeezeInterval);if($('spmEcModal'))$('spmEcModal').classList.remove('on');document.body.style.overflow=''}
function enhance(){document.querySelectorAll('.dayCard').forEach(card=>{const day=Number(card.querySelector('.dayNum')?.textContent||0),tag=card.querySelector('.tag')?.textContent||'';if(!SCHEDULE[day]||!/Control eyaculatorio/i.test(tag)||card.dataset.ecEnhanced)return;card.dataset.ecEnhanced='1';const area=card.querySelector('.interactive');if(!area)return;const meta=SCHEDULE[day],t=TECH[meta.tech],b=document.createElement('button');b.type='button';b.className='btn pri ecLaunch';b.textContent=`▶ Semana ${meta.week} · Sesión ${meta.session}/3 · ${t.name}`;b.onclick=e=>{e.stopPropagation();open(day)};area.prepend(b)})}
mount();enhance();new MutationObserver(enhance).observe(document.body,{childList:true,subtree:true});window.SPM_EJACULATORY_CONTROL={open,schedule:SCHEDULE};
})();
