(()=>{
const route={
3:{title:'Regulación autonómica antes de exigir respuesta',learn:'La respuesta eréctil puede deteriorarse cuando el cuerpo entra en modo de amenaza, vigilancia o prisa. La respiración no sustituye un tratamiento médico, pero puede ayudar a reducir activación y mejorar la capacidad de permanecer en la experiencia.',practice:'Haz 5 ciclos de respiración lenta: inhala 4 segundos, exhala 6 segundos y suelta mandíbula, abdomen, glúteos y periné. Después observa sensaciones agradables durante 2 minutos sin comprobar la firmeza.',measure:'Tensión corporal y presión por rendir antes/después, 0–10.',apply:'Úsalo antes de una práctica sexual o cuando notes que empiezas a vigilar la erección.',complete:'Guarda si bajó la tensión y si fue más fácil volver a sensaciones.',tool:'regulation'},
5:{title:'Mapa de estímulos que facilitan la respuesta eréctil',learn:'No toda estimulación produce la misma respuesta. Identificar qué tipo de contacto, fantasía, ritmo, contexto o anticipación favorece excitación ayuda a evitar depender de una sola forma de estimulación.',practice:'Selecciona los estímulos que suelen facilitar más tu excitación: contacto, fantasía, anticipación, novedad, ritmo, privacidad, conexión emocional o autoestimulación. Marca también los que te desconectan o aumentan presión.',measure:'Elige tus 3 facilitadores más potentes y 2 inhibidores principales.',apply:'En la próxima práctica modifica solo un factor y observa la respuesta.',complete:'Guarda tu mapa de facilitadores e inhibidores eréctiles.',tool:'stimuli'},
7:{title:'Revisión de Semana 1: ¿vascular, contextual o mixto?',learn:'SPM no diagnostica la causa de una dificultad eréctil, pero sí puede reconocer patrones que justifican distintos siguientes pasos. Una respuesta muy variable por contexto orienta a entrenar presión, atención y habilidades; un deterioro persistente con factores cardiometabólicos aumenta la importancia de revisión clínica y estilo de vida.',practice:'Revisa esta semana: erecciones espontáneas, respuesta con autoestimulación, respuesta con pareja, sueño, estrés, actividad física y factores médicos conocidos.',measure:'Marca qué grupo parece pesar más hoy: contexto/ansiedad, hábitos/metabolismo, respuesta globalmente reducida o patrón mixto.',apply:'SPM utilizará esta prioridad para la Semana 2 sin convertirla en un diagnóstico.',complete:'Guarda la hipótesis de trabajo y cualquier dato que deba revisarse clínicamente.',tool:'patternReview'},
9:{title:'Activación vascular: movimiento aeróbico progresivo',learn:'La actividad aeróbica regular tiene respaldo como intervención no farmacológica para mejorar salud cardiovascular y puede contribuir a mejorar función eréctil en algunos hombres. La progresión debe adaptarse a condición física y seguridad cardiovascular.',practice:'Elige una actividad aeróbica segura que ya toleres: caminar rápido, bicicleta, elíptica o similar. Empieza con una sesión manejable y registra duración y esfuerzo percibido. Si tienes enfermedad cardiovascular conocida, dolor torácico, falta de aire desproporcionada o restricciones médicas, no aumentes intensidad sin valoración.',measure:'Minutos realizados, esfuerzo percibido 0–10 y energía después de la sesión.',apply:'Planifica 2–4 oportunidades de movimiento esta semana y progresa gradualmente; no necesitas “entrenar duro” para empezar.',complete:'Guarda tu punto de partida de actividad aeróbica.',tool:'aerobic'},
14:{title:'Revisión de Semana 2: escoger la rama que más necesita trabajo',learn:'Después de dos semanas ya podemos dejar de tratar toda DE como si fuera igual. La siguiente fase debe priorizar el componente que sigue limitando más: inicio, firmeza, mantenimiento, recuperación, ansiedad o contexto.',practice:'Revisa tus registros y selecciona el punto con mayor margen de mejora.',measure:'Compara Día 8–14 en firmeza cuando fue evaluable, mantenimiento, presión y confianza.',apply:'La Semana 3 intensificará solo la rama que más lo necesita.',complete:'Guarda una prioridad principal y una secundaria.',tool:'branch'},
17:{title:'Exposición gradual a situaciones de mayor exigencia',learn:'Cuando la dificultad aparece principalmente al intentar penetrar o al pasar de estimulación a una situación más exigente, una exposición gradual puede reducir el salto brusco de presión. No es obligatoria y solo se usa si coincide con tu objetivo sexual.',practice:'Elige un nivel cómodo: 1) contacto erótico sin penetración, 2) estimulación genital con pausa libre, 3) aproximación a penetración sin obligación de continuar, 4) actividad penetrativa habitual. Avanza solo cuando el nivel previo se sienta manejable.',measure:'Presión anticipatoria, presencia y respuesta eréctil/no evaluable en cada nivel.',apply:'No avances para “probar” si puedes. Avanza cuando el nivel anterior ya no se siente como examen.',complete:'Guarda el nivel que puedes manejar con menor vigilancia.',tool:'gradedExposure'},
18:{title:'Comunicación de pareja que protege la respuesta',learn:'Ocultar una fluctuación o interpretar una pausa como fracaso puede aumentar presión para ambos. Una comunicación breve y funcional ayuda a mantener conexión sin convertir la erección en el centro de la experiencia.',practice:'Ensaya una frase: “si hacemos una pausa no significa que algo vaya mal”, “quiero seguir con lo que se siente bien”, o “prefiero no convertir esto en una prueba”.',measure:'Comodidad para comunicar 0–10 y presión anticipatoria antes/después.',apply:'Usa una frase real cuando sea pertinente y observa si disminuye la vigilancia.',complete:'Guarda la frase que mejor preserve conexión y flexibilidad.',tool:'partner'},
23:{title:'Flexibilidad eréctil: éxito no significa rigidez perfecta todo el tiempo',learn:'La función sexual normal admite fluctuaciones. Convertir cualquier cambio de firmeza en fracaso puede reforzar ansiedad y evitación. El objetivo es responder con flexibilidad y conservar placer, comunicación y capacidad de recuperación.',practice:'Identifica una regla rígida que uses contigo mismo, por ejemplo “debo estar completamente firme todo el tiempo”, y conviértela en una expectativa funcional.',measure:'Presión antes y después 0–10.',apply:'Ensaya la nueva expectativa durante una práctica real o imaginada.',complete:'Guarda la reformulación que más reduzca exigencia.',tool:'flexibility'},
26:{title:'Preparar el siguiente ciclo: mantenimiento, intensificación o revisión clínica',learn:'El siguiente paso no debe ser repetir automáticamente los mismos 28 días. SPM usa respuesta, adherencia, seguridad y driver secundario para decidir qué conservar y qué cambiar.',practice:'Clasifica tus módulos en tres grupos: funcionaron y deben mantenerse; necesitan una progresión distinta; ya no aportan suficiente valor. Si usas un tratamiento médico prescrito, registra adherencia, dudas y efectos para revisarlos con tu profesional sin modificar dosis por tu cuenta.',measure:'Elige máximo dos objetivos para el siguiente ciclo y marca si existe un problema médico o de tratamiento que requiera revisión.',apply:'Si existe un driver secundario importante, el próximo ciclo puede alternar módulos de ambos dominios en lugar de reiniciar el mismo programa.',complete:'SPM prepara un Ciclo 2 personalizado o mantenimiento según tu evolución.',tool:'nextCycle'}
};
function isErection(){const t=(document.getElementById('profileTitle')?.textContent||'').toLowerCase();return t.includes('eréctil')||t.includes('erection');}
function slider(label){return `<label class="micro">${label}</label><div class="rangeRow"><input type="range" min="0" max="10" value="5"><b>5</b></div>`;}
function bind(root){root.querySelectorAll('.rangeRow').forEach(r=>{const i=r.querySelector('input'),b=r.querySelector('b');if(i&&b)i.addEventListener('input',()=>b.textContent=i.value);});}
function toolHtml(type){
 if(type==='regulation')return `<div class="erectionPlus"><b class="tag">Regulación</b>${slider('Tensión antes 0–10')}${slider('Tensión después 0–10')}</div>`;
 if(type==='stimuli')return `<div class="erectionPlus"><b class="tag">Mapa de estímulos</b><label style="display:block;margin:8px 0"><input type="checkbox"> Contacto</label><label style="display:block;margin:8px 0"><input type="checkbox"> Fantasía / anticipación</label><label style="display:block;margin:8px 0"><input type="checkbox"> Novedad</label><label style="display:block;margin:8px 0"><input type="checkbox"> Privacidad / tiempo</label><label style="display:block;margin:8px 0"><input type="checkbox"> Conexión emocional</label></div>`;
 if(type==='patternReview')return `<div class="erectionPlus"><b class="tag">Hipótesis de trabajo</b><select><option>Contexto / ansiedad pesa más</option><option>Hábitos / metabolismo pesan más</option><option>Respuesta globalmente reducida</option><option>Patrón mixto</option></select></div>`;
 if(type==='aerobic')return `<div class="erectionPlus"><b class="tag">Actividad aeróbica</b><label class="micro">Minutos realizados</label><input type="number" min="0" max="300" value="20">${slider('Esfuerzo percibido 0–10')}</div>`;
 if(type==='branch')return `<div class="erectionPlus"><b class="tag">Prioridad actual</b><select><option>Iniciar erección</option><option>Firmeza</option><option>Mantenimiento</option><option>Recuperación</option><option>Ansiedad / vigilancia</option><option>Contexto</option></select></div>`;
 if(type==='gradedExposure')return `<div class="erectionPlus"><b class="tag">Escalera de exposición</b><select><option>1 · Contacto sin penetración</option><option>2 · Estimulación genital</option><option>3 · Aproximación sin obligación</option><option>4 · Actividad habitual</option></select>${slider('Presión anticipatoria 0–10')}</div>`;
 if(type==='partner')return `<div class="erectionPlus"><b class="tag">Guión de pareja</b><button type="button" class="btn sec sm">Una pausa no significa fracaso</button> <button type="button" class="btn sec sm">Sigamos con lo que se siente bien</button></div>`;
 if(type==='flexibility')return `<div class="erectionPlus">${slider('Presión por firmeza perfecta 0–10')}<textarea rows="2" placeholder="Nueva expectativa flexible..."></textarea></div>`;
 if(type==='nextCycle')return `<div class="erectionPlus"><b class="tag">Ciclo siguiente</b><label style="display:block;margin:8px 0"><input type="checkbox"> Mantener lo que funcionó</label><label style="display:block;margin:8px 0"><input type="checkbox"> Intensificar un objetivo</label><label style="display:block;margin:8px 0"><input type="checkbox"> Integrar driver secundario</label><label style="display:block;margin:8px 0"><input type="checkbox"> Preparar revisión clínica</label></div>`;
 return '';
}
function enhanceCard(card,spec){if(card.dataset.erectionPlus==='1')return;card.dataset.erectionPlus='1';const h=card.querySelector('.dayTop h4');if(h)h.textContent=spec.title;const sm=card.querySelector('.dayTop p');if(sm)sm.textContent=spec.learn.slice(0,105)+'…';const ps=card.querySelectorAll('.lesson p');[spec.learn,spec.practice,spec.measure,spec.apply,spec.complete].forEach((v,i)=>{if(ps[i])ps[i].textContent=v;});const chips=card.querySelector('.moduleMeta');if(chips){const c=document.createElement('span');c.className='chip';c.textContent='DE · ruta avanzada';chips.appendChild(c);}const inter=card.querySelector('.interactive');if(inter&&!inter.querySelector('.erectionPlus')){const w=document.createElement('div');w.innerHTML=toolHtml(spec.tool);if(w.firstElementChild){inter.prepend(w.firstElementChild);bind(inter);}}}
function enhance(){if(!isErection())return;document.querySelectorAll('.dayCard').forEach(card=>{const d=Number(card.querySelector('.dayNum')?.textContent);if(route[d])enhanceCard(card,route[d]);});const sub=document.getElementById('coachSub');if(sub&&!document.getElementById('erectionPlusCoach'))sub.insertAdjacentHTML('afterend','<p class="micro" id="erectionPlusCoach">En DE el Coach también observa actividad aeróbica, presión por desempeño, contexto y el punto exacto donde se interrumpe la respuesta. Si hay deterioro persistente o señales cardiometabólicas relevantes, prioriza revisión clínica.</p>');}
function frameCycle(){
 const heroMicro=document.getElementById('heroMicro');
 if(heroMicro&&!document.getElementById('cycleIntro'))heroMicro.insertAdjacentHTML('afterend','<div id="cycleIntro" class="notice good" style="margin-top:14px"><b>Tu Ciclo Inicial SPM de 28 días</b><br><span class="micro" style="color:inherit">Estas cuatro semanas son el inicio de tu proceso: vamos a conocer mejor tu patrón, entrenar habilidades específicas, trabajar factores modificables y medir cómo responde tu función sexual. Pueden aparecer avances importantes durante este ciclo, pero consolidar cambios en función, confianza, hábitos y desempeño suele requerir más tiempo y práctica.</span></div>');
 const planSub=document.getElementById('planSub');
 if(planSub&&!document.getElementById('cyclePlanNote'))planSub.insertAdjacentHTML('afterend','<div id="cyclePlanNote" class="notice good" style="margin-top:12px"><b>28 días no es el final.</b><br><span class="micro" style="color:inherit">Este es tu primer ciclo de rehabilitación y entrenamiento. El objetivo es terminarlo con avances medibles, habilidades útiles y una ruta más precisa. Al final SPM decidirá si corresponde mantenimiento, un nuevo ciclo personalizado o una revisión clínica.</span></div>');
 const reassess=document.getElementById('reassessText');
 if(reassess)reassess.textContent='El Día 28 no cierra tu proceso: compara tu mapa inicial con tu evolución y define el siguiente paso. Según tus datos, SPM puede pasar a mantenimiento, crear un nuevo ciclo personalizado con objetivos distintos o recomendar valoración clínica.';
 document.querySelectorAll('.dayCard').forEach(card=>{const d=Number(card.querySelector('.dayNum')?.textContent);if(d===28&&!card.querySelector('.cycle28Note')){const body=card.querySelector('.dayBody');if(body)body.insertAdjacentHTML('afterbegin','<div class="notice good cycle28Note" style="margin-bottom:12px"><b>Fin del ciclo inicial, no del proceso.</b><br><span class="micro" style="color:inherit">Hoy no reinicias automáticamente. SPM compara tu línea de base con tu evolución y construye el siguiente paso según respuesta, adherencia, seguridad y objetivos pendientes.</span></div>');}});
}
let q=false;const schedule=()=>{if(q)return;q=true;setTimeout(()=>{q=false;enhance();frameCycle();},0)};new MutationObserver(schedule).observe(document.body,{subtree:true,childList:true,characterData:true});document.addEventListener('click',schedule);setTimeout(()=>{enhance();frameCycle();},50);
})();