(()=>{
const route={
1:{title:'Línea de base eréctil: cómo funciona hoy',learn:'Para mejorar una dificultad eréctil primero necesitamos distinguir inicio, firmeza, mantenimiento, contexto y variabilidad. Una sola experiencia no define tu función.',practice:'Registra cómo suelen ser tus erecciones recientes: facilidad para iniciarlas, nivel de firmeza, capacidad para mantenerlas y si hubo actividad suficiente para evaluarlo.',measure:'Usa el registro de firmeza SPM 0–4 y marca mantenimiento 0–10. Elige “no evaluable” si no hubo una experiencia reciente pertinente.',apply:'No intentes provocar una erección solo para medirla. Usa una experiencia natural si ocurre.',complete:'Guarda tu línea de base eréctil y el contexto.',tool:'baseline'},
2:{title:'Tu patrón eréctil real',learn:'La respuesta puede cambiar entre sueño, autoestimulación, pareja, posiciones, estrés o presión. Esa variación ayuda a entender qué factores están interfiriendo sin convertirla en un diagnóstico.',practice:'Compara tres contextos cuando puedas: erecciones espontáneas o matutinas, autoestimulación y actividad con pareja. Marca cuáles son mejores, peores o no evaluables.',measure:'Valora la diferencia entre contextos 0–10 y registra si el problema principal es iniciar, mantener o recuperar firmeza.',apply:'Durante la semana observa el patrón sin comprobar continuamente la erección.',complete:'SPM guarda el contexto que más modifica tu respuesta.',tool:'contexts'},
4:{title:'Salir del modo “comprobación”',learn:'Revisar mentalmente la firmeza cada pocos segundos puede aumentar presión y sacar la atención de las señales eróticas. El objetivo es aprender a volver a la experiencia.',practice:'Durante 5 minutos de contacto o imaginación erótica, cada vez que notes una comprobación mental cambia la atención hacia tres sensaciones: temperatura, presión y placer.',measure:'Cuenta cuántas veces te sorprendiste comprobando la erección y cuánto tardaste en volver a sensaciones.',apply:'Si aparece intimidad, usa la misma maniobra sin exigirte recuperar firmeza de inmediato.',complete:'Registra qué estímulo hizo más fácil dejar de vigilarte.',tool:'monitoring'},
6:{title:'Piso pélvico inteligente para la respuesta eréctil',learn:'El piso pélvico puede participar en la función sexual, pero no todos necesitan fortalecimiento. Dolor, tensión o dificultad para relajar cambian completamente la ruta.',practice:'Realiza conciencia y relajación suave. Solo si no hay dolor ni tensión marcada, añade contracciones breves y controladas sin apretar glúteos o abdomen.',measure:'Registra facilidad para contraer y, sobre todo, para relajar 0–10. Si aparece dolor o aumento de tensión, detén el fortalecimiento.',apply:'Observa si aprietas involuntariamente durante estrés o actividad sexual.',complete:'SPM decide entre relajación, coordinación o progresión; no Kegels automáticos.',tool:'pelvic'},
8:{title:'Entrenamiento eréctil I: excitación sin examen',learn:'Una erección necesita excitación y contexto, no vigilancia. El primer entrenamiento específico busca permitir que la respuesta aparezca sin ponerla a prueba.',practice:'Reserva 8–10 minutos de estimulación agradable o imaginación erótica. No persigas una firmeza concreta. Cambia estímulo si disminuye interés y vuelve a sensaciones cuando aparezca monitoreo.',measure:'Registra excitación 0–10, firmeza 0–4 o no evaluable y presión por rendir 0–10.',apply:'Termina antes de convertir la práctica en una prueba de “funcionamiento”.',complete:'Guarda qué condiciones facilitaron la respuesta.',tool:'erectionPractice'},
10:{title:'Entrenamiento eréctil II: sostener sin perseguir',learn:'Mantener la erección no significa conservar exactamente la misma rigidez todo el tiempo. El entrenamiento busca tolerar pequeñas fluctuaciones sin entrar en alarma.',practice:'Durante una práctica de baja presión, mantén el estímulo que resulte agradable. Si notas una disminución, evita comprobar; respira, cambia ritmo o estímulo y observa si la respuesta vuelve.',measure:'Registra cuántas fluctuaciones aparecieron, cuántas pudiste manejar sin ansiedad alta y mantenimiento percibido 0–10.',apply:'No fuerces la continuación si la excitación desaparece; una pausa también es una respuesta válida.',complete:'Compara control y presión con el Día 8.',tool:'maintenance'},
11:{title:'Protocolo de recuperación de firmeza',learn:'Una caída de firmeza puede ser transitoria. Tener un protocolo evita que el episodio se convierta en una cadena de preocupación → comprobación → mayor pérdida de respuesta.',practice:'Ensaya cinco pasos: 1) deja de evaluar, 2) exhala lentamente, 3) cambia estímulo o ritmo, 4) vuelve a una sensación agradable, 5) retoma solo si reaparece interés o respuesta.',measure:'Puntúa confianza para manejar una fluctuación 0–10 antes y después del ensayo.',apply:'Si ocurre una pérdida real de firmeza, usa el protocolo una sola vez antes de decidir si continuar, pausar o cambiar la actividad.',complete:'Identifica qué paso te ayudó más.',tool:'recovery'},
12:{title:'¿Iniciar, mantener o recuperar?',learn:'No todos los perfiles eréctiles fallan en el mismo punto. Identificar el momento crítico permite elegir una habilidad más específica.',practice:'Selecciona tu patrón dominante actual: dificultad para iniciar, firmeza insuficiente, pérdida durante estimulación, pérdida al intentar penetrar, pérdida durante el coito o recuperación lenta.',measure:'Marca cuál ocurre con mayor frecuencia y qué nivel de presión lo acompaña.',apply:'SPM prioriza la siguiente práctica según ese momento crítico.',complete:'Tu ruta queda enfocada al punto donde más se interrumpe la respuesta.',tool:'pattern'},
13:{title:'Confianza eréctil basada en evidencia',learn:'La confianza útil no consiste en repetirte que “todo saldrá bien”, sino en reconocer señales reales de capacidad conservada y habilidades que ya puedes usar.',practice:'Identifica tres evidencias personales: una erección espontánea o contextual, una experiencia donde mantuviste mejor la respuesta y una habilidad que ya sabes aplicar cuando fluctúa.',measure:'Confianza para afrontar una experiencia sexual 0–10 antes y después.',apply:'Antes de la intimidad recuerda una evidencia concreta, no una exigencia de perfección.',complete:'Guarda tu evidencia de capacidad y recuperación.',tool:'confidence'},
15:{title:'Transferencia eréctil gradual',learn:'Una habilidad aprendida en baja presión debe trasladarse gradualmente a contextos más reales. Saltar directamente a la situación más exigente puede reactivar vigilancia y ansiedad.',practice:'Elige un nivel: 1) práctica individual, 2) contacto con pareja sin meta genital, 3) estimulación genital sin meta de penetración, 4) actividad sexual habitual. Empieza donde la presión sea manejable.',measure:'Registra firmeza/no evaluable, presión anticipatoria y capacidad de permanecer presente.',apply:'Avanza solo si el nivel actual se siente manejable; repetir no es retroceder.',complete:'Guarda el nivel que hoy puedes manejar con confianza.',tool:'ladder'},
16:{title:'Focalización sensorial I para DE',learn:'Cuando se retira temporalmente la obligación de penetrar o mantener una erección, puede disminuir el monitoreo y aumentar la atención a estímulos eróticos y agradables.',practice:'Realiza 10–15 minutos de contacto sensorial sin meta de penetración ni orgasmo. Si hay pareja, ambos deben estar de acuerdo. Si no, adapta la práctica a autoexploración consciente.',measure:'Presencia, presión, disfrute y respuesta eréctil si fue evaluable.',apply:'Si aparece una erección, no cambies inmediatamente el objetivo de la práctica para “aprovecharla”.',complete:'Registra qué tipo de contacto facilitó más presencia y excitación.',tool:'sensate'},
19:{title:'Focalización sensorial II: más erotismo, misma flexibilidad',learn:'La progresión puede incluir mayor estímulo erótico manteniendo una regla: la erección es una respuesta que observamos, no una prueba que debemos aprobar.',practice:'Amplía gradualmente el estímulo y practica cambios de ritmo, pausas breves y retorno a sensaciones sin comprobar la firmeza continuamente.',measure:'Firmeza 0–4/no evaluable, mantenimiento 0–10, disfrute y presión.',apply:'Mantén lo que favorece excitación y reduce lo que activa vigilancia.',complete:'Compara con el Día 16.',tool:'erectionPractice'},
20:{title:'Diseña condiciones favorables para la erección',learn:'Sueño, cansancio, privacidad, alcohol, estrés, prisa, conflicto, expectativa y tipo de estímulo pueden modificar la respuesta eréctil.',practice:'Construye un contexto realista para una experiencia sexual: menos cansancio, mayor privacidad, menor alcohol, tiempo suficiente, estímulos que funcionen y una expectativa flexible.',measure:'Cuenta cuántos inhibidores modificables pudiste reducir.',apply:'Pon a prueba este contexto si surge una oportunidad real.',complete:'Guarda tus mejores condiciones de respuesta.',tool:'planner'},
21:{title:'Revisión vascular y metabólica',learn:'La salud eréctil comparte factores con salud cardiovascular y metabólica. El programa no diagnostica enfermedad vascular, pero sí identifica hábitos y señales que justifican prevención o revisión clínica.',practice:'Revisa actividad física, sueño, tabaco/nicotina, alcohol, alimentación, peso/perímetro si deseas registrarlo y controles de presión, glucosa o lípidos si ya los tienes.',measure:'Elige uno o dos factores modificables con mayor margen y marca si existe algún dato médico pendiente de revisión.',apply:'Continúa solo con cambios seguros de estilo de vida; no ajustes medicamentos por tu cuenta.',complete:'Integra tu prioridad vascular/metabólica al mantenimiento.',tool:'vascular'},
22:{title:'Repite las dos estrategias eréctiles que más funcionaron',learn:'Consolidar no significa sumar técnicas indefinidamente. Significa conservar las estrategias que realmente mejoraron presencia, firmeza, mantenimiento o recuperación.',practice:'Selecciona tus dos herramientas con mayor utilidad: regulación, cambio de estímulo, protocolo de recuperación, Sensate Focus, contexto, comunicación o piso pélvico si correspondía.',measure:'Utilidad 0–10 de cada estrategia y esfuerzo requerido.',apply:'Integra una de ellas a una experiencia habitual.',complete:'Marca cuáles conservarás después del ciclo.',tool:'best'},
24:{title:'Tu tendencia eréctil empieza a verse',learn:'El progreso no se mide por una sola erección. Buscamos tendencias en inicio, firmeza, mantenimiento, recuperación, presión, confianza y contexto.',practice:'Revisa tus registros de las últimas semanas y separa tres categorías: mejoró, sigue igual, necesita más atención.',measure:'Compara firmeza y mantenimiento cuando fueron evaluables, más confianza y presión.',apply:'No cambies simultáneamente las estrategias que sí están funcionando.',complete:'Se prepara la reevaluación final.',tool:'progress'},
25:{title:'Prevención de recaídas eréctiles',learn:'Estrés, cansancio, enfermedad, cambios de pareja o una experiencia difícil pueden producir retrocesos temporales. Tener un plan reduce el riesgo de convertirlos en ansiedad anticipatoria.',practice:'Construye tu plan “si ocurre X, haré Y” para pérdida de firmeza, ausencia de respuesta, presión alta o una experiencia sexual difícil.',measure:'Confianza para recuperarte después de un mal día 0–10.',apply:'Incluye cuándo repetir habilidades y cuándo pedir valoración clínica si el cambio es persistente o nuevo.',complete:'Guarda tu plan de recuperación.',tool:'ifthen'},
27:{title:'Ensayo autónomo de manejo eréctil',learn:'Antes de cerrar el ciclo, SPM busca comprobar si puedes reconocer tu patrón y responder sin depender de instrucciones constantes.',practice:'Diseña una práctica o experiencia usando tus mejores condiciones y las dos herramientas eréctiles que más te sirvieron.',measure:'Firmeza/no evaluable, mantenimiento, presión, confianza y sensación de autonomía.',apply:'Adapta la estrategia a tu vida real y acepta variabilidad normal.',complete:'Registra qué necesitas para sostener el avance.',tool:'erectionPractice'},
28:{title:'Reevaluación eréctil y siguiente ciclo',learn:'El final del ciclo compara tu punto de partida con múltiples dimensiones, no con una experiencia aislada.',practice:'Revisa inicio de erección, firmeza, mantenimiento, recuperación, diferencias por contexto, confianza, presión y hábitos. Si una escala validada es aplicable en la versión clínica/comercial, se utilizará respetando su ventana y permisos.',measure:'Compara inicio vs. final y marca qué cambió de forma sostenida.',apply:'SPM propone mantenimiento, un nuevo ciclo personalizado o revisión clínica según tus datos y seguridad.',complete:'Cierra el ciclo con un Performance Map actualizado.',tool:'progress'}
};
function isErection(){const t=(document.getElementById('profileTitle')?.textContent||'').toLowerCase();return t.includes('eréctil')||t.includes('erection');}
function slider(label,min=0,max=10,val=5){return `<label class="micro">${label}</label><div class="rangeRow"><input type="range" min="${min}" max="${max}" value="${val}"><b>${val}</b></div>`;}
function bindSliders(root){root.querySelectorAll('.rangeRow').forEach(r=>{const i=r.querySelector('input'),b=r.querySelector('b');if(i&&b)i.addEventListener('input',()=>b.textContent=i.value);});}
function toolHtml(type){
 if(type==='baseline')return `<div class="erectionTool"><b class="tag">Registro eréctil SPM</b><label class="micro">Firmeza reciente</label><select class="firmness"><option value="na">No evaluable</option><option value="0">0 · Sin respuesta eréctil</option><option value="1">1 · Aumento leve, poca firmeza</option><option value="2">2 · Firmeza parcial</option><option value="3">3 · Firmeza funcional pero no máxima</option><option value="4">4 · Firmeza completa</option></select>${slider('Mantenimiento percibido 0–10')}</div>`;
 if(type==='contexts')return `<div class="erectionTool"><b class="tag">Comparador de contextos</b><div class="coachGrid"><label class="field">Matutina/espontánea<select><option>No evaluable</option><option>Mejor</option><option>Similar</option><option>Peor</option></select></label><label class="field">Autoestimulación<select><option>No evaluable</option><option>Mejor</option><option>Similar</option><option>Peor</option></select></label><label class="field">Con pareja<select><option>No evaluable</option><option>Mejor</option><option>Similar</option><option>Peor</option></select></label></div>${slider('Variación entre contextos 0–10')}</div>`;
 if(type==='monitoring')return `<div class="erectionTool"><b class="tag">Contador de comprobaciones</b><div class="timer">0</div><button type="button" class="btn sec sm countCheck">+ Noté que estaba comprobando</button></div>`;
 if(type==='pelvic')return `<div class="erectionTool"><b class="tag">Ruta de piso pélvico</b>${slider('Facilidad para relajar 0–10')}<label style="display:block;margin:8px 0"><input type="checkbox" class="pelvicPain"> Apareció dolor o tensión marcada</label><p class="micro">Si aparece dolor/tensión, prioriza relajación y no progreses a fortalecimiento automático.</p></div>`;
 if(type==='erectionPractice')return `<div class="erectionTool"><b class="tag">Práctica eréctil guiada</b>${slider('Excitación 0–10')}${slider('Presión por rendir 0–10')}<label class="micro">Firmeza</label><select><option>No evaluable</option><option>0</option><option>1</option><option>2</option><option>3</option><option>4</option></select></div>`;
 if(type==='maintenance')return `<div class="erectionTool"><b class="tag">Manejo de fluctuaciones</b>${slider('Mantenimiento 0–10')}${slider('Control ante una caída 0–10')}<label style="display:block;margin:8px 0"><input type="checkbox"> Pude evitar la comprobación constante</label><label style="display:block;margin:8px 0"><input type="checkbox"> Pude cambiar estímulo/ritmo sin alarma</label></div>`;
 if(type==='recovery')return `<div class="erectionTool"><b class="tag">Protocolo 5 pasos</b><ol class="micro"><li>Dejar de evaluar</li><li>Exhalar lentamente</li><li>Cambiar estímulo o ritmo</li><li>Volver a una sensación agradable</li><li>Retomar solo si reaparece respuesta/interés</li></ol>${slider('Confianza para recuperarme 0–10')}</div>`;
 if(type==='pattern')return `<div class="erectionTool"><b class="tag">Momento crítico</b><select><option>Dificultad para iniciar</option><option>Firmeza insuficiente</option><option>Pérdida durante estimulación</option><option>Pérdida al intentar penetrar</option><option>Pérdida durante el coito</option><option>Recuperación lenta</option></select>${slider('Presión asociada 0–10')}</div>`;
 if(type==='confidence')return `<div class="erectionTool">${slider('Confianza eréctil 0–10')}</div>`;
 if(type==='ladder')return `<div class="erectionTool"><b class="tag">Nivel de transferencia</b><select><option>1 · Práctica individual</option><option>2 · Contacto sin meta genital</option><option>3 · Estimulación genital sin penetración</option><option>4 · Actividad sexual habitual</option></select>${slider('Presión anticipatoria 0–10')}</div>`;
 if(type==='sensate')return `<div class="erectionTool"><b class="tag">Focalización sensorial</b><label style="display:block;margin:8px 0"><input type="checkbox"> Sin meta de penetración</label><label style="display:block;margin:8px 0"><input type="checkbox"> Sin obligación de mantener erección</label><label style="display:block;margin:8px 0"><input type="checkbox"> Atención a sensaciones agradables</label>${slider('Presencia 0–10')}</div>`;
 if(type==='planner')return `<div class="erectionTool"><b class="tag">Contexto favorable</b><textarea rows="2" placeholder="¿Qué cambiarás hoy? Sueño, privacidad, alcohol, prisa, estímulo, comunicación..."></textarea></div>`;
 if(type==='vascular')return `<div class="erectionTool"><b class="tag">Chequeo vascular/metabólico</b><label style="display:block;margin:8px 0"><input type="checkbox"> Actividad física</label><label style="display:block;margin:8px 0"><input type="checkbox"> Sueño/recuperación</label><label style="display:block;margin:8px 0"><input type="checkbox"> Alimentación cardiometabólica</label><label style="display:block;margin:8px 0"><input type="checkbox"> Alcohol/tabaco/nicotina</label><label style="display:block;margin:8px 0"><input type="checkbox"> Tengo controles médicos pendientes</label></div>`;
 if(type==='best')return `<div class="erectionTool"><b class="tag">Mis dos mejores herramientas</b><input type="text" placeholder="Herramienta 1"><input type="text" placeholder="Herramienta 2"></div>`;
 if(type==='progress')return `<div class="erectionTool"><b class="tag">Tendencia eréctil</b>${slider('Facilidad para iniciar 0–10')}${slider('Mantenimiento 0–10')}${slider('Confianza 0–10')}${slider('Presión 0–10')}</div>`;
 if(type==='ifthen')return `<div class="erectionTool"><b class="tag">Plan si-entonces</b><textarea rows="2" placeholder="Si aparece una caída o una experiencia difícil, entonces..."></textarea></div>`;
 return '';
}
function enhanceCard(card,spec){if(card.dataset.erectionRoute==='1')return;card.dataset.erectionRoute='1';const h=card.querySelector('.dayTop h4');if(h)h.textContent=spec.title;const summary=card.querySelector('.dayTop p');if(summary)summary.textContent=spec.learn.slice(0,105)+'…';const ps=card.querySelectorAll('.lesson p');[spec.learn,spec.practice,spec.measure,spec.apply,spec.complete].forEach((v,i)=>{if(ps[i])ps[i].textContent=v;});const chips=card.querySelector('.moduleMeta');if(chips){const c=document.createElement('span');c.className='chip';c.textContent='Ruta específica de DE';chips.appendChild(c);}const inter=card.querySelector('.interactive');if(inter&&!inter.querySelector('.erectionTool')){const box=document.createElement('div');box.innerHTML=toolHtml(spec.tool);if(box.firstElementChild){inter.prepend(box.firstElementChild);bindSliders(inter);const count=inter.querySelector('.countCheck');if(count){let n=0;count.addEventListener('click',()=>{n++;const t=inter.querySelector('.timer');if(t)t.textContent=n;});}}}}
function enhanceCoach(){if(!isErection())return;const grid=document.querySelector('#coach .coachGrid');if(!grid||grid.querySelector('#erectionFirmness'))return;grid.insertAdjacentHTML('beforeend',`<div class="field erectionCoachField"><label>Firmeza de la experiencia</label><select id="erectionFirmness"><option value="na">No evaluable</option><option value="0">0</option><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option></select></div><div class="field erectionCoachField"><label>Mantenimiento 0–10</label><input id="erectionMaintenance" type="number" min="0" max="10" value="6"></div><div class="field erectionCoachField"><label>Presión por rendir 0–10</label><input id="erectionPressure" type="number" min="0" max="10" value="5"></div>`);const sub=document.getElementById('coachSub');if(sub&&!document.getElementById('erectionCoachNote'))sub.insertAdjacentHTML('afterend','<p class="micro" id="erectionCoachNote">Ruta DE: el Coach añade firmeza, mantenimiento y presión solo cuando son evaluables. No necesitas provocar una erección para completar el registro.</p>');const save=document.getElementById('coachSave');if(save&&!save.dataset.erectionBound){save.dataset.erectionBound='1';save.addEventListener('click',()=>setTimeout(()=>{const f=document.getElementById('erectionFirmness')?.value,m=Number(document.getElementById('erectionMaintenance')?.value),p=Number(document.getElementById('erectionPressure')?.value);let msg='';if(f==='na')msg='Hoy no hubo una experiencia eréctil evaluable; SPM mantiene el foco en adherencia, sueño, estrés, confianza y habilidades.';else if(p>=8)msg='La presión fue alta. La ruta prioriza regulación y reducción de monitoreo antes de intensificar la exposición.';else if(Number(f)<=2||m<=4)msg='La respuesta fue limitada hoy. SPM no interpreta un evento aislado como fracaso; conviene revisar contexto, repetir la habilidad y vigilar tendencia.';else if(Number(f)>=3&&m>=6)msg='La respuesta fue funcional y relativamente estable. Si la tendencia se repite, SPM puede progresar gradualmente la transferencia.';const d=document.getElementById('coachDecision');if(d&&msg){let x=document.getElementById('erectionCoachDecision');if(!x){x=document.createElement('div');x.id='erectionCoachDecision';x.className='notice good';x.style.marginTop='8px';d.appendChild(x);}x.textContent=msg;}},0));}}
}
function enhance(){if(!isErection())return;const intro=document.getElementById('weekIntro');if(intro&&!intro.dataset.erectionRoute){intro.dataset.erectionRoute='1';intro.insertAdjacentHTML('beforeend','<div class="micro" style="margin-top:8px">Ruta DE: inicio, firmeza, mantenimiento, recuperación, contexto, presión, salud vascular/metabólica y seguimiento longitudinal.</div>');}document.querySelectorAll('.dayCard').forEach(card=>{const d=Number(card.querySelector('.dayNum')?.textContent);if(route[d])enhanceCard(card,route[d]);});enhanceCoach();}
let queued=false;const schedule=()=>{if(queued)return;queued=true;setTimeout(()=>{queued=false;enhance();},0);};new MutationObserver(schedule).observe(document.body,{subtree:true,childList:true,characterData:true});document.addEventListener('click',schedule);setTimeout(enhance,80);
})();