(()=>{
const SB_URL='https://jogirmziqjlsttbbarcx.supabase.co',SB_KEY='sb_publishable_jXmxa5K6ThK9C8DPIxmVVQ_mbuLWVaf';
const db=window.supabase?.createClient(SB_URL,SB_KEY);let timer=null,running=false,voice=true,current=null,remaining=0;
const targetDays=new Set([8,10,12,15,17,19,22,25,27]);
const names={erection:'Rendimiento eréctil',ejaculation:'Control eyaculatorio',confidence:'Confianza y ansiedad de desempeño',desire:'Deseo y excitación',wellbeing:'Bienestar y conexión sexual',lifestyle:'Hábitos protectores'};
const skillBank={
 confidence:{foundation:['Regulación de presión','Respira lento y reconoce pensamientos de desempeño sin discutir con ellos.',18],build:['Atención fuera del examen','Vuelve a sensaciones corporales y contacto en lugar de comprobar tu rendimiento.',22],integrate:['Exposición con flexibilidad','Permanece en una situación de baja presión aceptando variaciones sin interpretarlas como fracaso.',25],autonomy:['Autogestión de ansiedad','Si aparece presión, aplica respiración y redirección de atención sin detener toda la experiencia.',25]},
 erection:{foundation:['Respuesta sin vigilancia','Permite que la excitación aparezca sin comprobar la firmeza de forma repetitiva.',22],build:['Mantenimiento flexible','Conserva atención en placer, estímulo y respiración mientras la respuesta cambia naturalmente.',25],integrate:['Recuperación eréctil','Si la firmeza fluctúa, baja presión, cambia estímulo y retoma solo si la respuesta reaparece.',25],autonomy:['Manejo autónomo de fluctuaciones','Usa tu estrategia de recuperación sin convertir una caída transitoria en alarma.',25]},
 ejaculation:{foundation:['Escala de excitación','Reconoce tu nivel de excitación antes de llegar al límite.',22],build:['Intervención temprana','Cambia ritmo o pausa uno o dos niveles antes de perder control.',25],integrate:['Start–Stop integrado','Aumenta, estabiliza, reduce o pausa y reinicia solo tras recuperar control.',30],autonomy:['Control autónomo del umbral','Regula ritmo sin esperar al punto de no retorno.',25]},
 desire:{foundation:['Reducir frenos','Identifica cansancio, prisa, conflicto o presión que interfieran.',20],build:['Activar facilitadores','Favorece contexto, estímulo, conexión o fantasía que aumenten interés.',25],integrate:['Activación gradual','Permite que el deseo aparezca con tiempo suficiente, sin obligación de respuesta inmediata.',25],autonomy:['Autonomía del deseo','Construye una experiencia alrededor de los facilitadores que mejor funcionan para ti.',25]},
 wellbeing:{foundation:['Conexión sin meta','Prioriza comodidad, presencia y comunicación sobre un resultado sexual específico.',20],build:['Focalización sensorial','Atiende contacto, textura, temperatura y disfrute sin examen de rendimiento.',25],integrate:['Comunicación integrada','Ajusta ritmo y expectativas mediante mensajes simples y claros.',25],autonomy:['Flexibilidad sexual','Permite que una experiencia satisfactoria tenga distintas formas, ritmos y resultados.',25]},
 lifestyle:{foundation:['Preparación del contexto','Revisa sueño, estrés, alcohol, energía y condiciones de privacidad.',18],build:['Microcambio protector','Elige un solo hábito sostenible para mejorar esta semana.',20],integrate:['Condiciones favorables','Reduce interferencias modificables antes de una experiencia sexual.',20],autonomy:['Mantenimiento sostenible','Conserva únicamente hábitos protectores que realmente puedas mantener.',20]}
};
const phaseForDay=d=>d<=10?'foundation':d<=15?'build':d<=22?'integrate':'autonomy';
const pairPriority={
 'erection|ejaculation':['confidence','erection','ejaculation'],
 'erection|confidence':['confidence','erection'],
 'ejaculation|confidence':['confidence','ejaculation'],
 'desire|erection':['desire','confidence','erection'],
 'desire|confidence':['confidence','desire'],
 'desire|ejaculation':['confidence','desire','ejaculation'],
 'erection|wellbeing':['confidence','wellbeing','erection'],
 'ejaculation|wellbeing':['confidence','wellbeing','ejaculation']
};
function keyOf(a,b){return [a,b].sort().join('|')}
function chooseDomains(map){const scores=map.domain_scores||{},primary=map.primary_domain||'lifestyle',secondary=map.secondary_domain;let ordered=[primary];if(secondary&&secondary!==primary)ordered.push(secondary);Object.entries(scores).filter(([k])=>names[k]&&k!==primary&&k!==secondary).sort((a,b)=>a[1]-b[1]).slice(0,1).forEach(([k])=>ordered.push(k));const pair=pairPriority[keyOf(primary,secondary||'')];if(pair){ordered=[...pair,...ordered]}return [...new Set(ordered)].slice(0,3)}
function progressiveSteps(domains,day){const phase=phaseForDay(day),steps=[];const use=domains.filter(d=>skillBank[d]);use.forEach((d,i)=>{const s=skillBank[d][phase]||skillBank[d].build;if(!s)return;steps.push([s[0],s[1],Math.max(15,s[2]-i*2),d])});if(day===17&&use.includes('ejaculation')&&use.includes('erection'))steps.push(['Integración DE + control','Practica cambios de ritmo manteniendo atención en sensación. Si baja la firmeza, evita acelerar por miedo; si sube demasiado la excitación, reduce antes del límite.',28,'mixed']);if(day===19&&use.includes('confidence'))steps.push(['Transferencia sin examen','Lleva las habilidades aprendidas a una situación de intimidad real o imaginada sin buscar un resultado perfecto.',25,'mixed']);if(day===22)steps.push(['Selecciona lo que funciona','Elige dos herramientas con mejor utilidad y elimina repeticiones innecesarias.',22,'mixed']);if(day===25)steps.push(['Plan si ocurre X','Define una respuesta concreta para tu principal riesgo: ansiedad, pérdida de firmeza, ascenso rápido de excitación o bajo deseo.',22,'mixed']);if(day===27)steps.push(['Ensayo autónomo integrado','Combina tus dos habilidades principales sin guía detallada. El objetivo es flexibilidad y recuperación, no perfección.',30,'mixed']);return steps}
function speak(t){if(!voice||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='es-CO';u.rate=.9;speechSynthesis.speak(u)}
const css=`.mxOverlay{position:fixed;inset:0;z-index:10040;background:#02080bed;display:grid;place-items:center;padding:18px;overflow:auto}.mxOverlay[hidden]{display:none!important}.mxBox{width:min(800px,96%);background:linear-gradient(180deg,#10262e,#071419);border:1px solid #31515b;border-radius:24px;padding:22px;color:#f3f7f8}.mxTop{display:flex;justify-content:space-between;gap:12px}.mxClose{width:44px;height:44px;border-radius:12px;border:1px solid #ffffff22;background:transparent;color:#fff}.mxBadge{display:inline-block;padding:7px 10px;border-radius:999px;background:#78e1c41c;color:#78e1c4;font-size:12px;font-weight:800}.mxStage{margin:16px 0;padding:22px;min-height:330px;border:1px solid #ffffff12;border-radius:20px;background:#061116;text-align:center;display:grid;align-content:center;gap:14px}.mxVisual{display:flex;gap:8px;justify-content:center;flex-wrap:wrap}.mxChip{padding:10px 13px;border-radius:999px;border:1px solid #31515b;background:#11272f}.mxChip.on{background:#78e1c4;color:#052119}.mxCount{font-size:46px;font-weight:950;color:#78e1c4}.mxCue{font-size:22px;font-weight:900}.mxSub{color:#a8bbc1;line-height:1.55;max-width:640px;margin:auto}.mxProgress{height:7px;background:#17333a;border-radius:99px;overflow:hidden}.mxProgress i{display:block;height:100%;background:#78e1c4;width:0}.mxActions{display:flex;gap:9px;justify-content:center;flex-wrap:wrap}.mxBtn{border:0;border-radius:13px;padding:12px 16px;font-weight:850;background:#78e1c4;color:#052119}.mxBtn.sec{background:#11272f;color:#fff;border:1px solid #31515b}.mxRate{display:grid;grid-template-columns:1fr 1fr;gap:12px}.mxRate input{width:100%}.mxLaunch{margin-right:8px}@media(max-width:620px){.mxBox{padding:15px}.mxRate{grid-template-columns:1fr}}`;
const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
const ov=document.createElement('div');ov.className='mxOverlay';ov.hidden=true;ov.innerHTML=`<div class="mxBox" role="dialog" aria-modal="true"><div class="mxTop"><div><span class="mxBadge">SPM • Ruta mixta progresiva</span><h2 id="mxTitle"></h2><p class="micro" id="mxMeta"></p></div><button class="mxClose" aria-label="Cerrar">×</button></div><div class="mxProgress"><i></i></div><div class="mxStage"><div class="mxVisual"></div><div class="mxCount">Listo</div><div class="mxCue">Integración progresiva</div><div class="mxSub"></div></div><div class="mxRate" hidden><label>Control/confianza antes: <b id="mxPreV">5</b>/10<input id="mxPre" type="range" min="0" max="10" value="5"></label><label>Control/confianza después: <b id="mxPostV">5</b>/10<input id="mxPost" type="range" min="0" max="10" value="5"></label></div><div class="mxActions"><button id="mxStart" class="mxBtn">Comenzar ruta integrada</button><button id="mxVoice" class="mxBtn sec">Voz: activada</button><button id="mxPause" class="mxBtn sec" hidden>Pausar</button><button id="mxSave" class="mxBtn" hidden>Guardar sesión</button></div></div>`;document.body.appendChild(ov);const $=s=>ov.querySelector(s);
function visual(domains){return domains.map((d,i)=>`<span class="mxChip${i===0?' on':''}" data-domain="${d}">${names[d]||d}</span>`).join('')}
async function open(day){const {data:{user}}=await db.auth.getUser();if(!user)return;const {data:plans}=await db.from('plans').select('id,performance_map_id').eq('user_id',user.id).eq('status','active').order('created_at',{ascending:false}).limit(1);const plan=plans?.[0];if(!plan)return;const {data:map}=await db.from('performance_maps').select('primary_domain,secondary_domain,domain_scores').eq('id',plan.performance_map_id).maybeSingle();if(!map)return;const domains=chooseDomains(map);if(domains.length<2)return;const steps=progressiveSteps(domains,day);current={user,plan,map,domains,day,steps,step:0,total:0,totalTarget:steps.reduce((a,s)=>a+s[2],0)};$('#mxTitle').textContent=`Día ${day} · ${domains.map(d=>names[d]).join(' + ')}`;$('#mxMeta').textContent=`Fase ${phaseForDay(day)} · una sola ruta integrada, sin repetir habilidades ya aprendidas`;$('.mxVisual').innerHTML=visual(domains);$('.mxCount').textContent='Listo';$('.mxCue').textContent='Tu combinación de hoy';$('.mxSub').textContent='SPM integra tus dominios en una secuencia progresiva: primero regulación y base, luego habilidad específica, después transferencia y autonomía.';$('.mxRate').hidden=true;$('#mxStart').hidden=false;$('#mxPause').hidden=true;$('#mxSave').hidden=true;$('.mxProgress i').style.width='0';ov.hidden=false;speak($('.mxSub').textContent)}
function runStep(){if(!running)return;const [cue,sub,dur,domain]=current.steps[current.step];remaining=dur;$('.mxCue').textContent=cue;$('.mxSub').textContent=sub;$('.mxCount').textContent=remaining+'s';[...ov.querySelectorAll('.mxChip')].forEach(x=>x.classList.toggle('on',x.dataset.domain===domain||domain==='mixed'));speak(cue+'. '+sub);clearInterval(timer);timer=setInterval(()=>{if(!running)return;remaining--;current.total++;$('.mxCount').textContent=Math.max(0,remaining)+'s';$('.mxProgress i').style.width=Math.min(100,current.total/current.totalTarget*100)+'%';if(remaining<=0){clearInterval(timer);current.step++;if(current.step>=current.steps.length)finish();else runStep()}},1000)}
function start(){running=true;current.step=0;current.total=0;$('#mxStart').hidden=true;$('#mxPause').hidden=false;runStep()}
function pause(){if(running){running=false;clearInterval(timer);$('#mxPause').textContent='Continuar';speak('Pausa.')}else{running=true;$('#mxPause').textContent='Pausar';runStep()}}
function finish(){running=false;clearInterval(timer);$('.mxProgress i').style.width='100%';$('.mxCount').textContent='✓';$('.mxCue').textContent='Sesión integrada completada';$('.mxSub').textContent='SPM guardará qué dominios se integraron y cómo cambió tu sensación de control o confianza.';$('.mxRate').hidden=false;$('#mxPause').hidden=true;$('#mxSave').hidden=false;speak('Sesión integrada completada.')}
async function save(){if(!current)return close();$('#mxSave').disabled=true;await db.from('activity_completions').upsert({user_id:current.user.id,plan_id:current.plan.id,day_number:current.day,module_key:'mixed_guided_day_'+current.day,metric_value:Number($('#mxPost').value),metadata:{guided:true,mixed:true,domains:current.domains,phase:phaseForDay(current.day),pre:Number($('#mxPre').value),post:Number($('#mxPost').value),duration_seconds:current.total,completed_at:new Date().toISOString()}},{onConflict:'plan_id,day_number,module_key'});$('#mxSave').disabled=false;close();document.dispatchEvent(new CustomEvent('spm:mixed-guided-saved',{detail:{day:current?.day,domains:current?.domains}}))}
function close(){clearInterval(timer);running=false;if('speechSynthesis'in window)speechSynthesis.cancel();ov.hidden=true}
$('.mxClose').onclick=close;$('#mxStart').onclick=start;$('#mxPause').onclick=pause;$('#mxSave').onclick=save;$('#mxVoice').onclick=()=>{voice=!voice;$('#mxVoice').textContent='Voz: '+(voice?'activada':'desactivada');if(!voice&&'speechSynthesis'in window)speechSynthesis.cancel()};$('#mxPre').oninput=e=>$('#mxPreV').textContent=e.target.value;$('#mxPost').oninput=e=>$('#mxPostV').textContent=e.target.value;
async function enhance(){const grid=document.getElementById('dayGrid');if(!grid)return;const {data:{user}}=await db.auth.getUser();if(!user)return;const {data:plans}=await db.from('plans').select('performance_map_id').eq('user_id',user.id).eq('status','active').order('created_at',{ascending:false}).limit(1);const plan=plans?.[0];if(!plan)return;const {data:map}=await db.from('performance_maps').select('primary_domain,secondary_domain,domain_scores').eq('id',plan.performance_map_id).maybeSingle();if(!map||chooseDomains(map).length<2)return;[...grid.querySelectorAll('.dayCard')].forEach(card=>{if(card.dataset.mixedGuided)return;const day=Number(card.querySelector('.dayNum')?.textContent);if(!targetDays.has(day))return;const box=card.querySelector('.interactive');if(!box)return;const b=document.createElement('button');b.type='button';b.className='btn pri mxLaunch';b.textContent='◆ Iniciar ruta mixta progresiva';b.onclick=e=>{e.stopPropagation();open(day)};box.prepend(b);card.dataset.mixedGuided='1'})}
const grid=document.getElementById('dayGrid');if(grid)new MutationObserver(()=>enhance()).observe(grid,{childList:true,subtree:true});setTimeout(enhance,900);
})();