window.SPM_MODULES={
phases:[
 {id:1,name_es:'ENTENDER',name_en:'UNDERSTAND',days:[1,2,3,4,5,6,7],intro_es:'Línea de base, seguridad, reconocimiento de patrones y regulación.',intro_en:'Baseline, safety, pattern recognition and regulation.'},
 {id:2,name_es:'ENTRENAR',name_en:'TRAIN',days:[8,9,10,11,12,13,14],intro_es:'Habilidades dirigidas y repetición guiada según tu Performance Map.',intro_en:'Targeted skills and guided repetition based on your Performance Map.'},
 {id:3,name_es:'APLICAR',name_en:'APPLY',days:[15,16,17,18,19,20,21],intro_es:'Transferencia gradual a situaciones reales de intimidad cuando corresponde.',intro_en:'Gradual transfer to real intimacy when appropriate.'},
 {id:4,name_es:'CONSOLIDAR',name_en:'CONSOLIDATE',days:[22,23,24,25,26,27,28],intro_es:'Consolidar lo que funciona, ganar flexibilidad y preparar la reevaluación.',intro_en:'Consolidate what works, build flexibility and prepare reassessment.'}
],
profiles:{
 erection:{label_es:'Rendimiento eréctil',label_en:'Erection performance'},
 ejaculation:{label_es:'Control eyaculatorio',label_en:'Ejaculatory control'},
 desire:{label_es:'Deseo y excitación',label_en:'Desire and arousal'},
 confidence:{label_es:'Confianza y ansiedad de desempeño',label_en:'Confidence and performance anxiety'},
 wellbeing:{label_es:'Bienestar y conexión sexual',label_en:'Sexual wellbeing and connection'},
 lifestyle:{label_es:'Optimización y hábitos protectores',label_en:'Optimization and protective habits'},
 mixed:{label_es:'Perfil mixto',label_en:'Mixed profile'}
},
days:[
 {d:1,title_es:'Tu punto de partida',title_en:'Your starting point',learn_es:'Tu progreso se entiende mejor cuando existe una línea de base clara. Hoy no buscamos juzgarte, sino saber desde dónde comienzas. La salud sexual también está influida por factores vasculares, metabólicos y de estilo de vida.',practice_es:'Completa tu Línea de Base SPM: confianza, satisfacción, deseo y la métrica principal de tu perfil. Si aplica, registra EHS o control eyaculatorio reciente. Añade un registro breve de hábitos: verduras/frutas, bebidas azucaradas, ultraprocesados, alcohol y regularidad de comidas.',measure_es:'Marca 0–10 tu confianza y satisfacción actual. Usa “no evaluable” si no hubo experiencia sexual reciente. En nutrición solo registramos frecuencia y patrón, no contamos calorías.',apply_es:'Observa hoy tu respuesta sexual sin intentar corregirla. Solo reconoce qué ocurre y en qué contexto. Si tienes enfermedad renal, diabetes tratada, alergias, trastorno de la conducta alimentaria o una dieta indicada por un profesional, SPM mantendrá la orientación nutricional en un nivel general y sugerirá revisión individual cuando corresponda.',complete_es:'Guarda tu punto de partida sexual y cardiometabólico.',interaction:'baseline'},
 {d:2,title_es:'Tu patrón real',title_en:'Your real pattern',learn_es:'Una dificultad puede cambiar según contexto, pareja, autoestimulación, estrés o expectativa. Esa variación también es información.',practice_es:'Identifica dos contextos en los que tu respuesta sexual suele ser mejor y dos en los que suele ser peor.',measure_es:'Valora cuánto cambia tu desempeño entre contextos: 0 nada, 10 muchísimo.',apply_es:'Si aparece una situación sexual, nota contexto, presión percibida y calidad de respuesta.',complete_es:'Registra el patrón dominante.',interaction:'context'},
 {d:3,title_es:'Respiración y regulación',title_en:'Breathing and regulation',learn_es:'La activación excesiva puede aumentar vigilancia, tensión y pérdida de control. Regular primero permite entrenar mejor después.',practice_es:'Realiza 5 ciclos guiados de respiración lenta: inhalar 4 s, exhalar 6 s.',measure_es:'Antes y después, puntúa tensión corporal 0–10.',apply_es:'Usa 2 ciclos antes de una práctica sexual o cuando notes presión por rendir.',complete_es:'Marca cuánto bajó tu tensión.',interaction:'breathing'},
 {d:4,title_es:'Atención sin examen',title_en:'Attention without testing',learn_es:'Cuando la mente evalúa continuamente erección, tiempo o desempeño, disminuye la atención a sensaciones agradables.',practice_es:'Durante 5 minutos dirige la atención a sensaciones corporales neutrales y agradables sin evaluar desempeño.',measure_es:'Puntúa cuántas veces te sorprendiste “comprobando” tu rendimiento.',apply_es:'En una situación íntima, cambia una pregunta de examen por una de experiencia: “¿qué estoy sintiendo ahora?”.',complete_es:'Registra qué facilitó estar presente.',interaction:'counter'},
 {d:5,title_es:'Mapa de facilitadores e inhibidores',title_en:'Turn-ons and turn-offs map',learn_es:'Deseo y excitación dependen de factores que facilitan y factores que frenan la respuesta.',practice_es:'Selecciona tus principales facilitadores e inhibidores: descanso, privacidad, presión, conflicto, alcohol, cansancio, prisa, conexión.',measure_es:'Elige los 2 factores con mayor impacto esta semana.',apply_es:'Modifica hoy al menos un factor controlable.',complete_es:'Guarda tu mapa personal.',interaction:'checklist'},
 {d:6,title_es:'Piso pélvico: primero identificar y relajar',title_en:'Pelvic floor: identify and relax first',learn_es:'El piso pélvico no siempre necesita fortalecimiento. Dolor o tensión requieren una ruta distinta a debilidad o poca conciencia.',practice_es:'Haz 5 ciclos suaves de conciencia: identifica, contrae levemente 2 s y relaja por completo 6 s. Si hay dolor o aumento de tensión, omite la contracción y practica solo relajación.',measure_es:'Puntúa facilidad para relajar 0–10 y registra dolor/tensión.',apply_es:'Observa si aprietas abdomen, glúteos o periné durante estrés o excitación.',complete_es:'SPM define tu ruta de piso pélvico según respuesta.',interaction:'pelvic'},
 {d:7,title_es:'Revisión de Semana 1',title_en:'Week 1 review',learn_es:'La primera semana busca comprender, no demostrar rendimiento. También buscamos detectar qué hábito cardiometabólico ofrece el cambio más sencillo y sostenible.',practice_es:'Revisa tus registros: contexto, tensión, confianza, sueño, estrés, adherencia y tu patrón alimentario inicial. Elige solo un objetivo nutricional para la siguiente semana.',measure_es:'Elige qué variable mejoró, cuál sigue interfiriendo y qué práctica fue más útil. En nutrición marca el área con mayor margen: vegetales/frutas, bebidas azucaradas, ultraprocesados, alcohol o regularidad.',apply_es:'Selecciona una prioridad concreta para Semana 2. No cambies todo a la vez.',complete_es:'El Daily Coach decide progresar, repetir o simplificar y conserva un único objetivo nutricional activo.',interaction:'review'},
 {d:8,title_es:'Habilidad principal I',title_en:'Primary skill I',learn_es:'Desde hoy entrenas la habilidad más relacionada con tu driver principal.',practice_es:'SPM te muestra una práctica específica según tu perfil: recuperación de firmeza, control de excitación, activación de deseo o reducción de monitoreo.',measure_es:'Puntúa dificultad de la práctica y sensación de control 0–10.',apply_es:'Haz una repetición breve en un contexto de baja presión.',complete_es:'Registra si la técnica fue comprensible y útil.',interaction:'profileSkill'},
 {d:9,title_es:'Escala de excitación 0–10',title_en:'Arousal scale 0–10',learn_es:'Reconocer niveles de excitación permite intervenir antes de perder firmeza, control o presencia.',practice_es:'Usa la escala 0–10 y aprende a identificar tres zonas: baja, óptima y cercana al límite.',measure_es:'Selecciona el nivel en que normalmente notas que pierdes control o empiezas a vigilarte.',apply_es:'Durante autoestimulación o intimidad, identifica tu nivel sin intentar cambiarlo de inmediato.',complete_es:'Guarda tu umbral personal.',interaction:'arousal'},
 {d:10,title_es:'Habilidad principal II',title_en:'Primary skill II',learn_es:'La repetición funciona mejor cuando se modifica una sola variable por vez. Lo mismo ocurre con los hábitos: un cambio pequeño y sostenido suele ser más útil que una restricción intensa difícil de mantener.',practice_es:'Repite la habilidad principal con una progresión pequeña: más duración, menos pausas o mayor exposición según tu perfil.',measure_es:'Compara sensación de control con el Día 8. Registra si cumpliste tu objetivo nutricional de la semana.',apply_es:'Usa la técnica solo si se siente segura y manejable. Como microacción cardiometabólica, incorpora hoy una porción adicional de verdura o fruta entera si no tienes una restricción dietaria específica.',complete_es:'Daily Coach decide si progresas o repites y evita añadir un segundo cambio nutricional hasta que el primero sea manejable.',interaction:'profileSkill'},
 {d:11,title_es:'Recuperación ante una caída',title_en:'Recovery after a setback',learn_es:'Una fluctuación no equivale a fracaso. Saber recuperarse evita que un evento aislado se convierta en ansiedad anticipatoria.',practice_es:'Ensaya un protocolo breve: parar evaluación, respirar, cambiar estímulo, reconectar con sensación y retomar solo si surge respuesta.',measure_es:'Puntúa confianza para manejar una fluctuación 0–10.',apply_es:'Si aparece una dificultad real, aplica el protocolo sin forzar resultado.',complete_es:'Registra qué paso ayudó más.',interaction:'steps'},
 {d:12,title_es:'Entrenamiento dirigido por perfil',title_en:'Profile-directed training',learn_es:'Tu programa no necesita todas las técnicas disponibles; necesita las correctas en el orden correcto.',practice_es:'Completa el módulo asignado por tu Performance Map.',measure_es:'Puntúa utilidad percibida, dificultad y respuesta.',apply_es:'Haz una aplicación corta en contexto relevante.',complete_es:'SPM conserva, retira o cambia el módulo según tu respuesta.',interaction:'profileSkill'},
 {d:13,title_es:'Confianza basada en evidencia personal',title_en:'Evidence-based confidence',learn_es:'La confianza mejora cuando se apoya en experiencias concretas, no en autosugestión.',practice_es:'Identifica tres señales reales de capacidad conservada o progreso: una respuesta corporal, una habilidad aprendida y una situación manejada mejor.',measure_es:'Confianza antes y después 0–10.',apply_es:'Antes de una experiencia, recuerda una evidencia concreta en vez de exigir un resultado perfecto.',complete_es:'Guarda tu evidencia personal.',interaction:'confidence'},
 {d:14,title_es:'Revisión de Semana 2',title_en:'Week 2 review',learn_es:'Entrenar no significa avanzar cada día; a veces la mejor decisión es repetir o bajar intensidad. En nutrición buscamos patrón cardioprotector, no prohibiciones absolutas.',practice_es:'Revisa adherencia, sueño, estrés, confianza, resultado específico del objetivo y el cambio alimentario iniciado. Si el primer objetivo ya es estable, selecciona una sustitución sencilla: reducir una bebida azucarada o un snack ultraprocesado y reemplazarlo por una alternativa menos procesada.',measure_es:'Clasifica la semana: progreso claro, progreso parcial, estable o más difícil. Registra cuántas veces lograste la sustitución, sin etiquetar alimentos como “buenos” o “malos”.',apply_es:'Acepta la recomendación del Coach para Semana 3. No se eliminan “todas las harinas”; cuando aplique, se priorizan fuentes menos refinadas e integrales.',complete_es:'Se actualiza tu ruta sexual y cardiometabólica.',interaction:'review'},
 {d:15,title_es:'Transferencia gradual',title_en:'Gradual transfer',learn_es:'Las habilidades se consolidan cuando pasan de un entorno de práctica a situaciones reales sin aumentar presión demasiado rápido.',practice_es:'Elige el nivel de transferencia adecuado: práctica individual, intimidad sin meta de penetración o actividad sexual habitual.',measure_es:'Ansiedad anticipatoria 0–10 antes y después.',apply_es:'Realiza solo el nivel que se sienta manejable.',complete_es:'Registra respuesta y aprendizaje.',interaction:'ladder'},
 {d:16,title_es:'Focalización sensorial I',title_en:'Sensate focus I',learn_es:'Reducir la meta de “rendir” permite recuperar atención a placer, contacto y excitación.',practice_es:'10–15 minutos de contacto sensorial sin objetivo de penetración ni orgasmo, si existe pareja y ambos desean participar.',measure_es:'Puntúa presencia, presión y disfrute.',apply_es:'Termina antes de convertirlo en una prueba.',complete_es:'Registra qué sensaciones fueron más fáciles de atender.',interaction:'timer'},
 {d:17,title_es:'Control de ritmo',title_en:'Pacing control',learn_es:'Cambiar intensidad, velocidad o estímulo puede ayudar a regular excitación sin desconectarse. A nivel vascular, SPM favorece patrones alimentarios cardioprotectores en lugar de “alimentos afrodisíacos”.',practice_es:'Entrena 3 ciclos de aumentar, estabilizar y reducir intensidad. En perfil eyaculatorio puede usarse pausa/Start–Stop; en otros perfiles se usa regulación de ritmo y atención.',measure_es:'Nivel máximo de excitación y sensación de control. Registra si esta semana has incorporado fuentes cardioprotectoras como leguminosas, frutos secos, pescado, aceite de oliva o vegetales variados.',apply_es:'Prueba un cambio de ritmo intencional en una experiencia relevante. Como microacción nutricional, incorpora una fuente cardioprotectora que ya toleres y sea compatible con tus indicaciones médicas.',complete_es:'Registra qué cambio funcionó y cuál alimento te resulta más fácil mantener.',interaction:'cycles'},
 {d:18,title_es:'Comunicación que reduce presión',title_en:'Pressure-reducing communication',learn_es:'La presión disminuye cuando necesidades, ritmo y expectativas pueden comunicarse sin interpretar cada cambio como fracaso.',practice_es:'Elige y adapta un guion breve: “Quiero ir más despacio”, “prefiero que hoy no tengamos una meta”, “si paro un momento no significa que algo vaya mal”.',measure_es:'Comodidad para comunicar 0–10.',apply_es:'Usa una frase real cuando sea pertinente.',complete_es:'Registra su efecto.',interaction:'script'},
 {d:19,title_es:'Focalización sensorial II',title_en:'Sensate focus II',learn_es:'La progresión aumenta estímulo conservando la regla de no convertir la experiencia en un examen.',practice_es:'Amplía la práctica sensorial incluyendo zonas erógenas si se siente cómodo, manteniendo pausas y atención.',measure_es:'Presencia, disfrute y monitoreo 0–10.',apply_es:'Detente si aumenta presión de forma marcada.',complete_es:'Compara con Día 16.',interaction:'timer'},
 {d:20,title_es:'Plan para una experiencia sexual',title_en:'Plan for a sexual experience',learn_es:'Preparar condiciones favorables no es controlar el resultado; es reducir interferencias modificables. Comidas muy abundantes o exceso de alcohol pueden empeorar energía, comodidad o respuesta en algunas personas, por lo que SPM ayuda a reconocer tu patrón sin imponer reglas universales.',practice_es:'Construye un plan breve: horario, privacidad, cansancio, alcohol, expectativas, comunicación, técnica principal y cómo te sientes con la comida previa a la intimidad.',measure_es:'Cuántos inhibidores pudiste reducir. Si consumiste alcohol o una comida muy abundante, registra si notaste algún cambio en energía, comodidad o respuesta.',apply_es:'Usa el plan si aparece una oportunidad real; si no, consérvalo para la próxima. Si identificas un patrón consistente, ajusta solo esa variable en la siguiente experiencia.',complete_es:'Registra qué factores estaban bajo tu control, sin atribuir un resultado sexual a un alimento aislado.',interaction:'planner'},
 {d:21,title_es:'Revisión de Semana 3',title_en:'Week 3 review',learn_es:'La transferencia se evalúa por calidad de experiencia, flexibilidad y recuperación, no solo por un resultado sexual perfecto.',practice_es:'Revisa experiencias reales o simuladas y qué habilidades lograste usar.',measure_es:'Compara confianza, presión, satisfacción y objetivo principal con la Semana 1.',apply_es:'Define qué habilidad merece consolidación.',complete_es:'SPM prepara tu semana final.',interaction:'review'},
 {d:22,title_es:'Repetir lo que sí funciona',title_en:'Repeat what works',learn_es:'Consolidar significa repetir las estrategias con mejor relación entre utilidad, esfuerzo y resultado.',practice_es:'Selecciona tus dos prácticas de mayor utilidad y repítelas de forma breve.',measure_es:'Utilidad actual 0–10 de cada una.',apply_es:'Integra una de ellas a tu rutina normal.',complete_es:'Marca cuál conservarás después del ciclo.',interaction:'selectBest'},
 {d:23,title_es:'Flexibilidad sexual',title_en:'Sexual flexibility',learn_es:'Una función sexual saludable admite variación. No todas las experiencias necesitan la misma intensidad, duración o secuencia.',practice_es:'Identifica una expectativa rígida y conviértela en una alternativa flexible.',measure_es:'Presión percibida antes/después.',apply_es:'Ensaya la alternativa en una situación real o imaginada.',complete_es:'Registra cómo cambió la presión.',interaction:'reframe'},
 {d:24,title_es:'Tu progreso empieza a verse',title_en:'Your progress becomes visible',learn_es:'A partir de hoy preparamos la comparación entre tu punto de partida y tu estado actual. Los hábitos vasculares y metabólicos se revisan como tendencias, no como explicación única de la evolución sexual.',practice_es:'Revisa tendencias de confianza, satisfacción, adherencia y métrica específica de tu perfil. Compara además tu patrón inicial con el actual en verduras/frutas, bebidas azucaradas, ultraprocesados, alcohol y fuentes cardioprotectoras.',measure_es:'Selecciona tres cambios: mejoró, sigue igual, necesita atención. Si quieres, registra peso o perímetro abdominal como dato opcional, nunca como requisito.',apply_es:'No cambies todo a la vez; conserva lo que funciona. Mantén solo los hábitos alimentarios que sean realistas y compatibles con tu salud.',complete_es:'Se inicia la reevaluación final y se identifican los hábitos cardiometabólicos con mejor adherencia.',interaction:'progress'},
 {d:25,title_es:'Prevención de recaídas',title_en:'Relapse prevention',learn_es:'Un día difícil no borra el aprendizaje. La prevención consiste en reconocer señales tempranas y responder antes de abandonar.',practice_es:'Construye tu plan “si ocurre X, haré Y” para estrés, pérdida de firmeza, menor control, baja libido o ansiedad.',measure_es:'Confianza para recuperarte 0–10.',apply_es:'Guarda una respuesta concreta para tu principal riesgo.',complete_es:'Tu plan queda disponible para el siguiente ciclo.',interaction:'ifthen'},
 {d:26,title_es:'Preparar el siguiente paso',title_en:'Prepare the next step',learn_es:'La continuidad solo tiene sentido si tus datos muestran una necesidad o un objetivo nuevo.',practice_es:'Elige qué deseas mantener, qué deseas mejorar y qué ya no necesita entrenamiento frecuente.',measure_es:'Prioriza máximo dos objetivos para después del Día 28.',apply_es:'Revisa si algún síntoma nuevo requiere valoración clínica.',complete_es:'SPM prepara opciones de continuidad.',interaction:'priorities'},
 {d:27,title_es:'Ensayo autónomo',title_en:'Independent rehearsal',learn_es:'Antes de cerrar el ciclo, el objetivo es comprobar qué puedes hacer sin depender de instrucciones constantes. Lo mismo ocurre con la nutrición: buscamos hábitos sostenibles, no un menú temporal.',practice_es:'Realiza de forma autónoma la práctica que más representa tu objetivo. Construye además tu “trío de mantenimiento nutricional”: tres hábitos simples que realmente puedas sostener, por ejemplo más vegetales, menos bebidas azucaradas y una fuente cardioprotectora frecuente.',measure_es:'Control, confianza y utilidad 0–10. Puntúa también qué tan sostenible te parece cada hábito alimentario: 0 imposible, 10 muy fácil de mantener.',apply_es:'Adáptala a tu vida real. Descarta objetivos alimentarios demasiado restrictivos o incompatibles con tus preferencias y salud.',complete_es:'Registra qué necesitarías para mantener tu entrenamiento y tus tres hábitos protectores.',interaction:'selfpractice'},
 {d:28,title_es:'Reevaluación y siguiente ciclo',title_en:'Reassessment and next cycle',learn_es:'El final del ciclo no se decide por sensación aislada: comparamos tu línea de base, tendencias y experiencia actual.',practice_es:'Completa la reevaluación final aplicable a tu perfil y revisa tu Performance Map actualizado. Incluye la evolución de los hábitos cardiometabólicos seleccionados.',measure_es:'Compara inicio vs. final: rigidez/control, confianza, deseo, satisfacción, hábitos, adherencia y cambios nutricionales sostenibles. SPM no atribuye una mejoría sexual a un alimento aislado.',apply_es:'SPM propone mantenimiento, un nuevo ciclo personalizado o revisión clínica según tus datos. Si persisten factores metabólicos relevantes, recomienda evaluación profesional en lugar de intensificar restricciones por cuenta propia.',complete_es:'Cierra el ciclo y guarda tu resumen sexual, conductual y cardiometabólico.',interaction:'reassessment'}
]
};