(()=>{
const desireText={
5:{title:'Mapa de deseo: aceleradores y frenos',learn:'El deseo no depende de una sola causa. Puede aumentar o disminuir según descanso, estrés, privacidad, conexión, rutina, presión, estímulos y estado general.',practice:'Identifica tus principales aceleradores del deseo y tus principales frenos. El objetivo no es obligarte a sentir deseo, sino reconocer qué condiciones lo facilitan.',measure:'Elige los dos factores que más influyeron en tu deseo durante la última semana.',apply:'Modifica hoy un factor que esté bajo tu control, aunque sea pequeño.',complete:'Guarda tus aceleradores y frenos prioritarios.',tool:'facilitators'},
8:{title:'Reactivación del deseo I: deseo responsivo',learn:'El deseo no siempre aparece antes del contacto. En algunas personas puede activarse después de comenzar una experiencia agradable, segura y sin presión.',practice:'Reserva 10 minutos para contacto, imaginación erótica o autoexploración sin exigir erección, penetración ni orgasmo. Solo observa si el interés aumenta una vez iniciada la experiencia.',measure:'Registra deseo antes y después de la práctica, de 0 a 10.',apply:'Si notas aumento progresivo, reconoce ese patrón como una posible vía de activación del deseo.',complete:'Guarda si tu deseo fue espontáneo, responsivo o no evaluable hoy.',tool:'beforeAfter'},
10:{title:'Reactivación del deseo II: repertorio de estímulos',learn:'La excitación sexual suele responder mejor cuando existe un repertorio variado de estímulos mentales, sensoriales, contextuales y relacionales.',practice:'Explora qué tipos de estímulo suelen despertar interés: fantasía, novedad, contacto, conversación, privacidad, ritmo, recuerdos eróticos, anticipación o conexión emocional.',measure:'Selecciona tres estímulos con mayor capacidad de activar interés y uno que actualmente lo inhiba.',apply:'Introduce solo uno de esos estímulos en una práctica breve, sin evaluar rendimiento.',complete:'Conserva tu repertorio personal de activadores.',tool:'stimuli'},
12:{title:'Ventana de activación del deseo',learn:'Esperar a que el deseo aparezca en condiciones desfavorables puede reforzar la sensación de que “ya no existe”. Crear una ventana favorable permite observar la respuesta sin presión.',practice:'Programa una ventana breve de intimidad o autoexploración en un momento con menos cansancio, interrupciones y presión. No debe tener una meta sexual obligatoria.',measure:'Valora energía, estrés y disposición antes de comenzar, y deseo al finalizar.',apply:'Compara esta experiencia con momentos de prisa, agotamiento o exigencia.',complete:'Identifica qué condiciones hicieron más fácil o más difícil la activación.',tool:'planner'},
13:{title:'Confianza para volver a sentir interés',learn:'Cuando una persona ha tenido varias experiencias de bajo deseo puede empezar a anticipar que “no tendrá ganas”, y esa expectativa puede aumentar presión y evitación.',practice:'Identifica tres señales reales de capacidad conservada: curiosidad, fantasía, respuesta corporal, disfrute del contacto o momentos en que el deseo sí apareció.',measure:'Puntúa tu confianza en que el deseo puede variar y recuperarse, de 0 a 10.',apply:'Antes de una experiencia, cambia “tengo que tener ganas” por “voy a observar qué aparece sin exigirme”.',complete:'Guarda una evidencia personal de capacidad de respuesta.',tool:'confidence'},
15:{title:'Escalera de intimidad sin presión',learn:'La reactivación del deseo suele funcionar mejor cuando la exposición aumenta de forma gradual y no salta directamente a una experiencia sexual exigente.',practice:'Elige un nivel: 1) cercanía/afecto, 2) contacto sensual, 3) estimulación erótica, 4) actividad sexual más completa. Comienza en el nivel que no genere presión alta.',measure:'Ansiedad anticipatoria y deseo antes/después, de 0 a 10.',apply:'Avanza de nivel solo si el actual se siente cómodo y útil.',complete:'Registra qué nivel permitió más presencia y curiosidad.',tool:'ladder'},
16:{title:'Focalización sensorial para reactivar excitación',learn:'Cuando se elimina temporalmente la obligación de rendir, el cerebro puede volver a prestar atención a contacto, placer y señales de excitación.',practice:'Realiza 10–15 minutos de contacto sensorial sin meta de penetración u orgasmo. Si existe pareja, ambos deben estar de acuerdo. Si no, puede adaptarse a autoexploración consciente.',measure:'Registra presencia, disfrute, presión y deseo antes/después.',apply:'Detente antes de convertir la práctica en una prueba de desempeño.',complete:'Identifica qué tipo de contacto o estímulo facilitó más respuesta.',tool:'sensate'},
18:{title:'Comunicar el deseo sin convertirlo en obligación',learn:'La presión relacional puede disminuir el deseo. Poder explicar ritmo, necesidad de tiempo y ausencia de una meta fija puede reducir esa presión.',practice:'Adapta una frase útil: “quiero empezar despacio”, “no necesito saber desde el principio hasta dónde llegaremos”, “quiero centrarme en disfrutar y ver qué aparece”.',measure:'Comodidad para comunicar tus necesidades, de 0 a 10.',apply:'Usa una frase real cuando corresponda.',complete:'Registra si la comunicación disminuyó presión o mejoró conexión.',tool:'scripts'},
19:{title:'Focalización sensorial II: ampliar estímulo',learn:'Si la primera fase fue cómoda, la siguiente progresión puede incluir mayor erotismo conservando la regla de no exigir un resultado concreto.',practice:'Amplía gradualmente el contacto hacia estímulos más eróticos y observa si el deseo aumenta, se mantiene o disminuye.',measure:'Deseo, excitación, disfrute y presión de 0 a 10.',apply:'Mantén los estímulos que favorecen respuesta y reduce los que aumentan presión.',complete:'Compara con tu práctica anterior.',tool:'sensate'},
20:{title:'Diseña un contexto favorable al deseo',learn:'El deseo puede verse afectado por factores simples pero repetidos: cansancio, falta de privacidad, alcohol, conflicto, horarios poco favorables o expectativas rígidas.',practice:'Construye tu contexto ideal realista: horario, privacidad, descanso, estímulos, comunicación, ritmo y ausencia de una meta obligatoria.',measure:'Cuenta cuántos inhibidores pudiste reducir.',apply:'Pon a prueba este contexto cuando exista una oportunidad real.',complete:'Guarda tu combinación de condiciones más favorables.',tool:'planner'},
22:{title:'Repite tus activadores más útiles',learn:'La consolidación no consiste en probar técnicas nuevas sin parar, sino en repetir lo que mostró utilidad real en tu caso.',practice:'Elige tus dos activadores de deseo con mejor respuesta hasta ahora y repítelos esta semana.',measure:'Utilidad de cada uno de 0 a 10.',apply:'Integra al menos uno a tu rutina de intimidad habitual.',complete:'Marca cuáles conservarás como herramientas de mantenimiento.',tool:'best'},
24:{title:'Tu curva de deseo empieza a verse',learn:'El progreso en deseo no siempre significa “tener ganas todo el tiempo”. Puede verse como mayor curiosidad, mayor facilidad para activarse, menos evitación o mejor disfrute.',practice:'Revisa tus registros de deseo espontáneo, deseo responsivo, excitación, disfrute y presión.',measure:'Identifica tres cambios: mejoró, se mantiene o necesita más trabajo.',apply:'Conserva los facilitadores que estén mostrando efecto.',complete:'Se prepara la comparación final con tu línea de base.',tool:'progress'},
27:{title:'Ensayo autónomo de activación del deseo',learn:'Antes de terminar el ciclo, SPM busca comprobar si puedes reconocer y utilizar tus propios facilitadores sin depender de instrucciones paso a paso.',practice:'Diseña y realiza una práctica usando tus mejores condiciones y estímulos, manteniendo una expectativa flexible.',measure:'Deseo antes/después, disfrute, presión y sensación de autonomía.',apply:'Adáptala a una situación real de tu vida.',complete:'Registra qué necesitarías para mantener este avance.',tool:'beforeAfter'},
28:{title:'Reevaluación del deseo y siguiente ciclo',learn:'El cambio se valora comparando tu punto de partida con varias dimensiones: interés, facilidad para activarte, deseo responsivo, satisfacción, evitación, confianza y hábitos.',practice:'Completa la reevaluación aplicable a tu perfil y revisa qué factores cambiaron de forma sostenida.',measure:'Compara inicio vs. final en deseo, excitación, satisfacción, confianza y presión.',apply:'SPM define mantenimiento, un nuevo ciclo personalizado o revisión clínica según tus datos.',complete:'Cierra el ciclo con un mapa actualizado y objetivos realistas.',tool:'progress'}
};
function isDesire(){const t=(document.getElementById('profileTitle')?.textContent||'').toLowerCase();return t.includes('deseo')||t.includes('desire');}
function slider(label){return `<label class="micro">${label}</label><div class="rangeRow"><input type="range" min="0" max="10" value="5"><b>5</b></div>`;}
function bindSliders(root){root.querySelectorAll('.rangeRow').forEach(r=>{const i=r.querySelector('input'),b=r.querySelector('b');if(i&&b)i.addEventListener('input',()=>b.textContent=i.value);});}
function toolHtml(type){
 if(type==='beforeAfter')return `<div class="desireTool"><b class="tag">Registro deseo responsivo</b>${slider('Deseo antes 0–10')}${slider('Deseo después 0–10')}</div>`;
 if(type==='facilitators')return `<div class="desireTool"><b class="tag">Mis aceleradores y frenos</b><label style="display:block;margin:8px 0"><input type="checkbox"> Descanso suficiente</label><label style="display:block;margin:8px 0"><input type="checkbox"> Privacidad / tiempo</label><label style="display:block;margin:8px 0"><input type="checkbox"> Conexión / afecto</label><label style="display:block;margin:8px 0"><input type="checkbox"> Novedad / fantasía</label><label style="display:block;margin:8px 0"><input type="checkbox"> Menor presión por rendir</label></div>`;
 if(type==='stimuli')return `<div class="desireTool"><b class="tag">Repertorio de estímulos</b><label style="display:block;margin:8px 0"><input type="checkbox"> Fantasía / imaginación</label><label style="display:block;margin:8px 0"><input type="checkbox"> Contacto físico</label><label style="display:block;margin:8px 0"><input type="checkbox"> Anticipación / conversación</label><label style="display:block;margin:8px 0"><input type="checkbox"> Novedad</label><label style="display:block;margin:8px 0"><input type="checkbox"> Conexión emocional</label></div>`;
 if(type==='planner')return `<div class="desireTool"><b class="tag">Planificador de contexto</b><label class="micro">¿Qué condición quiero mejorar hoy?</label><textarea rows="2" placeholder="Ej.: menos cansancio, más privacidad, más tiempo..."></textarea></div>`;
 if(type==='ladder')return `<div class="desireTool"><b class="tag">Nivel de intimidad</b><select><option>1 · Cercanía / afecto</option><option>2 · Contacto sensual</option><option>3 · Estimulación erótica</option><option>4 · Actividad sexual más completa</option></select>${slider('Presión anticipatoria 0–10')}</div>`;
 if(type==='sensate')return `<div class="desireTool"><b class="tag">Focalización sensorial</b><label style="display:block;margin:8px 0"><input type="checkbox"> Sin meta de penetración</label><label style="display:block;margin:8px 0"><input type="checkbox"> Sin obligación de orgasmo</label><label style="display:block;margin:8px 0"><input type="checkbox"> Atención a sensaciones agradables</label>${slider('Disfrute 0–10')}</div>`;
 if(type==='scripts')return `<div class="desireTool"><b class="tag">Guiones de comunicación</b><button type="button" class="btn sec sm">Quiero empezar despacio</button> <button type="button" class="btn sec sm">Sin meta obligatoria hoy</button> <button type="button" class="btn sec sm">Veamos qué aparece</button></div>`;
 if(type==='best')return `<div class="desireTool"><b class="tag">Mis dos mejores activadores</b><input type="text" placeholder="Activador 1"><input type="text" placeholder="Activador 2"></div>`;
 if(type==='confidence')return `<div class="desireTool">${slider('Confianza en mi capacidad de respuesta 0–10')}</div>`;
 if(type==='progress')return `<div class="desireTool">${slider('Deseo / interés actual 0–10')}${slider('Facilidad para activarme 0–10')}${slider('Satisfacción actual 0–10')}</div>`;
 return '';
}
function enhanceCard(card,spec){if(card.dataset.desireRoute==='1')return;card.dataset.desireRoute='1';const h=card.querySelector('.dayTop h4');if(h)h.textContent=spec.title;const summary=card.querySelector('.dayTop p');if(summary)summary.textContent=spec.learn.slice(0,105)+'…';const ps=card.querySelectorAll('.lesson p');[spec.learn,spec.practice,spec.measure,spec.apply,spec.complete].forEach((v,i)=>{if(ps[i])ps[i].textContent=v;});const chips=card.querySelector('.moduleMeta');if(chips){const c=document.createElement('span');c.className='chip';c.textContent='Ruta específica de deseo';chips.appendChild(c);}const inter=card.querySelector('.interactive');if(inter&&!inter.querySelector('.desireTool')){const box=document.createElement('div');box.innerHTML=toolHtml(spec.tool);if(box.firstElementChild){inter.prepend(box.firstElementChild);bindSliders(inter);}}
}
function enhance(){if(!isDesire())return;const intro=document.getElementById('weekIntro');if(intro&&!intro.dataset.desireRoute){intro.dataset.desireRoute='1';intro.insertAdjacentHTML('beforeend','<div class="micro" style="margin-top:8px">Ruta de bajo deseo: reactivación progresiva, deseo responsivo, facilitadores, reducción de inhibidores, conexión, hábitos y seguimiento.</div>');}document.querySelectorAll('.dayCard').forEach(card=>{const d=Number(card.querySelector('.dayNum')?.textContent);if(desireText[d])enhanceCard(card,desireText[d]);});const sub=document.getElementById('coachSub');if(sub&&!sub.dataset.desireRoute){sub.dataset.desireRoute='1';sub.insertAdjacentHTML('afterend','<p class="micro" id="desireCoachNote">En esta ruta el Coach observa deseo, facilidad de activación, presión, sueño, estrés y respuesta a los facilitadores sin obligarte a repetir cuestionarios completos.</p>');}}
let queued=false;const schedule=()=>{if(queued)return;queued=true;setTimeout(()=>{queued=false;enhance();},0);};new MutationObserver(schedule).observe(document.body,{subtree:true,childList:true,characterData:true});document.addEventListener('click',schedule);setTimeout(enhance,50);
})();