(()=>{
const SB_URL='https://jogirmziqjlsttbbarcx.supabase.co',SB_KEY='sb_publishable_jXmxa5K6ThK9C8DPIxmVVQ_mbuLWVaf';
const db=window.supabase?.createClient(SB_URL,SB_KEY);let timer=null,running=false,voice=true,current=null,remaining=0;
const targetDays=new Set([8,10,12,17,27]);
const routes={
 erection:{name:'Rendimiento eréctil',visual:'erection',days:{
  8:[['Preparación sin examen','Respira lento y deja de comprobar la firmeza. El objetivo es permitir respuesta, no exigirla.',15],['Atención a estímulo','Lleva la atención a sensaciones agradables, contacto y excitación sin vigilar cambios segundo a segundo.',30],['Recuperación tranquila','Si la respuesta fluctúa, baja presión, cambia estímulo y espera sin forzar.',20]],
  10:[['Entrada gradual','Empieza con estímulo cómodo y sin meta inmediata de penetración.',20],['Sostener sin vigilancia','Mantén atención en placer y respiración; evita comprobar constantemente la erección.',30],['Recuperar','Si disminuye la firmeza, pausa evaluación y vuelve al estímulo que resulte agradable.',20]],
  12:[['Reconocer señal','Identifica qué condiciones favorecen mejor respuesta: privacidad, tiempo, estímulo y menor presión.',20],['Entrenamiento dirigido','Practica mantener excitación sin convertir la firmeza en una prueba.',35],['Cerrar sin examen','Finaliza registrando sensación de control, no perfección del resultado.',15]],
  17:[['Sube estímulo','Aumenta intensidad gradualmente sin acelerar por miedo a perder firmeza.',15],['Estabiliza','Mantén un ritmo cómodo y presta atención a sensaciones.',15],['Reduce y recupera','Baja intensidad a propósito y comprueba que puedes volver a aumentar sin presión.',15]],
  27:[['Elige tu herramienta','Selecciona respiración, focalización sensorial o protocolo de recuperación.',15],['Ensayo autónomo','Aplica tu herramienta sin indicaciones constantes.',40],['Evalúa flexibilidad','Valora cuánto puedes responder a una fluctuación sin entrar en alarma.',15]]}},
 ejaculation:{name:'Control eyaculatorio',visual:'meter',days:{
  8:[['Reconoce tu escala','Ubica tu excitación actual de 0 a 10. El objetivo es detectar el ascenso antes del límite.',15],['Sube gradualmente','Aumenta estímulo manteniéndote en una zona manejable.',20],['Pausa antes del límite','Reduce o detén el estímulo antes del punto de no retorno.',20],['Reanuda con control','Continúa solo cuando la excitación haya descendido claramente.',20]],
  10:[['Sube','Aumenta de forma gradual sin buscar velocidad.',18],['Estabiliza','Mantén el nivel durante unos segundos.',12],['Start–Stop','Detén o reduce claramente antes del límite.',18],['Recupera','Respira y relaja piso pélvico antes de reiniciar.',15]],
  12:[['Umbral personal','Identifica en qué nivel empiezas a perder capacidad de decisión.',18],['Intervén antes','Practica cambiar ritmo o pausar uno o dos niveles antes.',25],['Reinicio consciente','Reanuda únicamente tras recuperar sensación de control.',20]],
  17:[['Aumenta','Sube intensidad de forma progresiva.',15],['Estabiliza','Mantente por debajo de tu umbral.',10],['Pausa','Reduce o detén estímulo y respira.',15],['Reanuda','Comienza de nuevo con menor intensidad.',15]],
  27:[['Define umbral','Recuerda tu zona de mayor control.',15],['Ensayo autónomo','Realiza varios cambios de ritmo sin esperar a estar al límite.',40],['Evalúa control','Valora si pudiste decidir cuándo bajar intensidad.',15]]}},
 confidence:{name:'Confianza y ansiedad de desempeño',visual:'focus',days:{
  8:[['Detecta vigilancia','Reconoce pensamientos tipo “tengo que rendir” sin discutir con ellos.',18],['Vuelve al cuerpo','Dirige atención a respiración, temperatura y contacto.',30],['Permite variación','Acepta cambios de excitación sin interpretarlos como fracaso.',20]],
  10:[['Respira','Haz dos ciclos lentos antes de comenzar.',15],['Exposición de baja presión','Permanece en una situación íntima o imaginada sin exigirte resultado.',35],['Cierra con evidencia','Registra una cosa que manejaste mejor que antes.',15]],
  12:[['Pensamiento automático','Identifica la predicción negativa principal.',18],['Respuesta flexible','Cámbiala por una frase funcional: “puedo ir despacio y ajustar”.',20],['Práctica corporal','Vuelve a sensación en vez de seguir evaluándote.',25]],
  17:[['Aumenta presencia','Acércate gradualmente a una situación que genere presión.',18],['Estabiliza','Quédate allí respirando sin intentar demostrar nada.',20],['Reduce presión','Baja intensidad antes de que la ansiedad domine.',18]],
  27:[['Sin guion','Empieza sin leer instrucciones durante la práctica.',15],['Resuelve una fluctuación','Si aparece ansiedad, aplica por ti mismo respiración y redirección de atención.',35],['Registra confianza','Valora tu capacidad para manejar el momento.',15]]}},
 desire:{name:'Deseo y excitación',visual:'desire',days:{
  8:[['Reduce frenos','Identifica cansancio, prisa, conflicto o presión que esté interfiriendo.',20],['Activa facilitadores','Elige contexto, estímulo, fantasía o conexión que favorezca excitación.',25],['Observa sin exigir','Permite que el deseo aparezca gradualmente.',20]],
  10:[['Prepara contexto','Reduce una interferencia controlable.',18],['Explora estímulo','Dedica atención a aquello que sí genera interés o placer.',30],['Registra respuesta','Valora curiosidad, excitación y deseo sin forzarlos.',18]],
  12:[['Mapa de deseo','Distingue deseo espontáneo de deseo que aparece después de iniciar contacto o estímulo.',20],['Activación gradual','Permite tiempo suficiente para que la excitación se construya.',30],['Conserva lo útil','Identifica qué facilitador funcionó mejor.',15]],
  17:[['Empieza suave','Inicia con estímulo de baja intensidad.',18],['Aumenta si aparece interés','Progresa solo cuando notes mayor conexión o excitación.',25],['Reduce si hay presión','Baja el ritmo si la práctica se convierte en obligación.',18]],
  27:[['Elige facilitador','Selecciona la condición que más favorece tu deseo.',15],['Ensayo autónomo','Construye una experiencia de baja presión alrededor de ese facilitador.',35],['Evalúa','Registra deseo, disfrute y sensación de libertad.',15]]}},
 wellbeing:{name:'Bienestar y conexión sexual',visual:'connection',days:{}},
 lifestyle:{name:'Optimización y hábitos protectores',visual:'path',days:{}}
};
function generic(route,day){return [['Preparación',`Tu ruta principal es ${route.name}. Prepara un contexto tranquilo y sin presión.`,18],['Práctica dirigida','Aplica la habilidad principal de tu ruta con intensidad manejable.',35],['Registro','Valora utilidad, dificultad y confianza de 0 a 10.',18]]}
function speak(t){if(!voice||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='es-CO';u.rate=.9;speechSynthesis.speak(u)}
const css=`.pgOverlay{position:fixed;inset:0;z-index:10020;background:#02080bed;display:grid;place-items:center;padding:18px;overflow:auto}.pgOverlay[hidden]{display:none!important}.pgBox{width:min(780px,96%);background:linear-gradient(180deg,#10262e,#071419);border:1px solid #31515b;border-radius:24px;padding:22px;color:#f3f7f8}.pgTop{display:flex;justify-content:space-between;gap:12px}.pgClose{width:44px;height:44px;border-radius:12px;border:1px solid #ffffff22;background:transparent;color:#fff}.pgBadge{display:inline-block;padding:7px 10px;border-radius:999px;background:#78e1c41c;color:#78e1c4;font-size:12px;font-weight:800}.pgStage{margin:16px 0;padding:22px;min-height:330px;border:1px solid #ffffff12;border-radius:20px;background:#061116;text-align:center;display:grid;align-content:center;gap:14px}.pgVisual{height:155px;display:grid;place-items:center}.pgRing{width:145px;height:145px;border:2px solid #78e1c4;border-radius:50%;display:grid;place-items:center;box-shadow:inset 0 0 0 18px #78e1c40b}.pgMeter{width:min(430px,90%);height:24px;border-radius:99px;background:linear-gradient(90deg,#3fbc9f 0 55%,#e5b866 55% 78%,#dc7777 78%);position:relative}.pgNeedle{position:absolute;top:-9px;width:5px;height:42px;background:white;left:35%;transition:left 1.5s}.pgPath{display:flex;gap:8px;align-items:center;justify-content:center;flex-wrap:wrap}.pgNode{padding:11px 14px;border:1px solid #31515b;border-radius:999px}.pgNode.on{background:#78e1c4;color:#052119}.pgCount{font-size:46px;font-weight:950;color:#78e1c4}.pgCue{font-size:22px;font-weight:900}.pgSub{color:#a8bbc1;line-height:1.55;max-width:620px;margin:auto}.pgProgress{height:7px;background:#17333a;border-radius:99px;overflow:hidden}.pgProgress i{display:block;height:100%;background:#78e1c4;width:0}.pgActions{display:flex;gap:9px;justify-content:center;flex-wrap:wrap}.pgBtn{border:0;border-radius:13px;padding:12px 16px;font-weight:850;background:#78e1c4;color:#052119}.pgBtn.sec{background:#11272f;color:#fff;border:1px solid #31515b}.pgRate{display:grid;grid-template-columns:1fr 1fr;gap:12px}.pgRate input{width:100%}@media(max-width:620px){.pgBox{padding:15px}.pgRate{grid-template-columns:1fr}}`;
const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
const ov=document.createElement('div');ov.className='pgOverlay';ov.hidden=true;ov.innerHTML=`<div class="pgBox" role="dialog" aria-modal="true"><div class="pgTop"><div><span class="pgBadge">SPM • Ruta personalizada</span><h2 id="pgTitle"></h2><p class="micro" id="pgMeta"></p></div><button class="pgClose" aria-label="Cerrar">×</button></div><div class="pgProgress"><i></i></div><div class="pgStage"><div class="pgVisual"></div><div class="pgCount">Listo</div><div class="pgCue">Entrenamiento según tu Performance Map</div><div class="pgSub"></div></div><div class="pgRate" hidden><label>Control/confianza antes: <b id="pgPreV">5</b>/10<input id="pgPre" type="range" min="0" max="10" value="5"></label><label>Control/confianza después: <b id="pgPostV">5</b>/10<input id="pgPost" type="range" min="0" max="10" value="5"></label></div><div class="pgActions"><button id="pgStart" class="pgBtn">Comenzar mi sesión</button><button id="pgVoice" class="pgBtn sec">Voz: activada</button><button id="pgPause" class="pgBtn sec" hidden>Pausar</button><button id="pgSave" class="pgBtn" hidden>Guardar sesión</button></div></div>`;document.body.appendChild(ov);const $=s=>ov.querySelector(s);
function visual(type){if(type==='meter')return'<div class="pgMeter"><i class="pgNeedle"></i></div>';if(type==='path')return'<div class="pgPath"><span class="pgNode on">Preparar</span><span>→</span><span class="pgNode">Practicar</span><span>→</span><span class="pgNode">Registrar</span></div>';return`<div class="pgRing">${type==='erection'?'Respuesta<br>sin examen':type==='desire'?'Deseo<br>gradual':type==='connection'?'Conexión<br>sin presión':'Atención<br>al cuerpo'}</div>`}
async function open(day){
 const {data:{user}}=await db.auth.getUser();if(!user)return;
 const {data:plans}=await db.from('plans').select('id,route_key,performance_map_id').eq('user_id',user.id).eq('status','active').order('created_at',{ascending:false}).limit(1);const plan=plans?.[0];if(!plan)return;
 let key=plan.route_key||'lifestyle';if(!routes[key])key='lifestyle';const route=routes[key],steps=route.days[day]||generic(route,day);
 current={user,plan,key,route,day,steps,step:0,total:0,totalTarget:steps.reduce((a,s)=>a+s[2],0)};
 $('#pgTitle').textContent=`Día ${day} · ${route.name}`;$('#pgMeta').textContent='Sesión diferente según tu perfil principal';$('.pgVisual').innerHTML=visual(route.visual);$('.pgCount').textContent='Listo';$('.pgCue').textContent='Tu entrenamiento de hoy';$('.pgSub').textContent=`SPM adaptó esta práctica a tu prioridad principal: ${route.name.toLowerCase()}.`;$('.pgRate').hidden=true;$('#pgStart').hidden=false;$('#pgPause').hidden=true;$('#pgSave').hidden=true;$('.pgProgress i').style.width='0';ov.hidden=false;speak($('.pgSub').textContent)
}
function animate(cue){const n=$('.pgNeedle');if(n)n.style.left=/sube|aumenta/i.test(cue)?'68%':/pausa|reduce|recupera/i.test(cue)?'30%':'52%';const nodes=[...ov.querySelectorAll('.pgNode')];nodes.forEach((x,i)=>x.classList.toggle('on',i===Math.min(current.step,nodes.length-1)))}
function runStep(){if(!running)return;const [cue,sub,dur]=current.steps[current.step];remaining=dur;$('.pgCue').textContent=cue;$('.pgSub').textContent=sub;$('.pgCount').textContent=remaining+'s';animate(cue);speak(cue+'. '+sub);clearInterval(timer);timer=setInterval(()=>{if(!running)return;remaining--;current.total++;$('.pgCount').textContent=Math.max(0,remaining)+'s';$('.pgProgress i').style.width=Math.min(100,current.total/current.totalTarget*100)+'%';if(remaining<=0){clearInterval(timer);current.step++;if(current.step>=current.steps.length)finish();else runStep()}},1000)}
function start(){running=true;current.step=0;current.total=0;$('#pgStart').hidden=true;$('#pgPause').hidden=false;runStep()}
function pause(){if(running){running=false;clearInterval(timer);$('#pgPause').textContent='Continuar';speak('Pausa.')}else{running=true;$('#pgPause').textContent='Pausar';runStep()}}
function finish(){running=false;clearInterval(timer);$('.pgProgress i').style.width='100%';$('.pgCount').textContent='✓';$('.pgCue').textContent='Sesión personalizada completada';$('.pgSub').textContent='Registra cómo cambió tu sensación de control o confianza. Esta información quedará asociada a tu ruta.';$('.pgRate').hidden=false;$('#pgPause').hidden=true;$('#pgSave').hidden=false;speak('Sesión personalizada completada.')}
async function save(){if(!current)return close();$('#pgSave').disabled=true;await db.from('activity_completions').upsert({user_id:current.user.id,plan_id:current.plan.id,day_number:current.day,module_key:`guided_profile_${current.key}_day_${current.day}`,metric_value:Number($('#pgPost').value),metadata:{guided:true,personalized:true,route_key:current.key,pre:Number($('#pgPre').value),post:Number($('#pgPost').value),duration_seconds:current.total,completed_at:new Date().toISOString()}},{onConflict:'plan_id,day_number,module_key'});$('#pgSave').disabled=false;close();document.dispatchEvent(new CustomEvent('spm:guided-saved',{detail:{day:current.day,profile:current.key}}))}
function close(){clearInterval(timer);running=false;if('speechSynthesis'in window)speechSynthesis.cancel();ov.hidden=true}
$('.pgClose').onclick=close;$('#pgStart').onclick=start;$('#pgPause').onclick=pause;$('#pgSave').onclick=save;$('#pgVoice').onclick=()=>{voice=!voice;$('#pgVoice').textContent='Voz: '+(voice?'activada':'desactivada')};$('#pgPre').oninput=e=>$('#pgPreV').textContent=e.target.value;$('#pgPost').oninput=e=>$('#pgPostV').textContent=e.target.value;
const grid=document.getElementById('dayGrid');if(grid)grid.addEventListener('click',e=>{const b=e.target.closest('.spmGuidedLaunch');if(!b)return;const card=b.closest('.dayCard'),day=Number(card?.querySelector('.dayNum')?.textContent);if(!targetDays.has(day))return;e.preventDefault();e.stopImmediatePropagation();open(day)},true);
})();